"""A single-file HTML report of one backtest.

The output is one ``.html`` file with nothing outside it: the stylesheet is
inline, every chart is SVG generated by the code below, there is no script tag,
no font download and no image reference.  That is deliberate.  A report is
usually read months after it was made, often on a machine that has never seen
this application, sometimes with no internet connection at all -- so a file that
needs a CDN to look right is a file that will one day look wrong.  It also means
the report can be attached to an email or dropped into a shared folder without
dragging a directory of assets along with it.

Everything the user typed -- strategy names, labels, tags, warnings -- goes
through :func:`html.escape` before it reaches the document.  A strategy called
``<script>alert(1)</script>`` renders as those characters and does nothing else.

The palette comes from :mod:`tradingbacktester.ui.theme` so the report and the
application agree on what green means.
"""

from __future__ import annotations

import html as _html
import logging
import math
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np

from ..core.errors import ReportError
from ..core.types import SignalExecution, SizingMode, Trade
from ..engine.results import BacktestResult
# Deliberately the Qt-free layer, not `ui.theme`: this module emits a string
# and must stay importable on a machine with no PySide6.
from ..core.presentation import (MONO_FONT_STACK, PALETTE, UI_FONT_STACK,
                                 duration as _duration, money as _money,
                                 number as _number, pct as _pct)
from .csv_export import (currency_symbol, describe_cost_model,
                         instrument_timezone, price_decimals, run_header_fields)

log = logging.getLogger(__name__)

#: Trades beyond this are omitted from the HTML table; the full list is the CSV
#: export.  A browser copes with a thousand rows; fifty thousand it does not.
MAX_TRADE_ROWS = 1000

#: Points kept when a curve is drawn.  Min/max decimation keeps every spike.
_CHART_POINTS = 1600

_MONTHS = ("Jan", "Feb", "Mar", "Apr", "May", "Jun",
           "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

#: The statistics panel's grouping, repeated here so the report and the
#: application present the same numbers under the same headings.  Each entry is
#: ``(key, label, format, signed, explanation)``.
METRIC_GROUPS: tuple[tuple[str, tuple[tuple[str, str, str, bool, str], ...]], ...] = (
    ("Profit and Loss", (
        ("net_profit", "Net profit", "money", True,
         "Ending balance minus starting capital, after all costs"),
        ("gross_profit", "Gross profit", "money", True,
         "Sum of every winning trade before costs"),
        ("gross_loss", "Gross loss", "money", True,
         "Sum of every losing trade before costs"),
        ("return_pct", "Return", "pct", True,
         "Net profit as a percentage of starting capital"),
        ("cagr", "CAGR", "pct", True, "Compound annual growth rate over the tested period"),
        ("starting_balance", "Starting balance", "money", False, ""),
        ("ending_balance", "Ending balance", "money", False, ""),
        ("profit_factor", "Profit factor", "ratio", True,
         "Gross profit divided by gross loss; above 1 is profitable"),
        ("expectancy", "Expectancy", "money", True, "Average net profit per trade"),
        ("expectancy_r", "Expectancy (R)", "ratio", True,
         "Average trade result in multiples of the initial risk"),
    )),
    ("Trades", (
        ("total_trades", "Total trades", "int", False, ""),
        ("winning_trades", "Winners", "int", False, ""),
        ("losing_trades", "Losers", "int", False, ""),
        ("win_rate", "Win rate", "pct", False, "Percentage of trades closed at a profit"),
        ("avg_trade", "Average trade", "money", True, ""),
        ("avg_win", "Average win", "money", True, ""),
        ("avg_loss", "Average loss", "money", True, ""),
        ("payoff_ratio", "Payoff ratio", "ratio", False,
         "Average win divided by average loss"),
        ("largest_win", "Largest win", "money", True, ""),
        ("largest_loss", "Largest loss", "money", True, ""),
        ("max_consecutive_wins", "Max consecutive wins", "int", False, ""),
        ("max_consecutive_losses", "Max consecutive losses", "int", False, ""),
        ("avg_trade_duration_seconds", "Average duration", "duration", False, ""),
        ("avg_bars_held", "Average bars held", "float1", False, ""),
        ("trades_per_year", "Trades per year", "float1", False, ""),
    )),
    ("Risk", (
        ("max_drawdown", "Max drawdown", "money", True,
         "Largest peak-to-trough fall in equity, in cash"),
        ("max_drawdown_pct", "Max drawdown %", "pct", True,
         "Largest peak-to-trough fall relative to the running peak"),
        ("max_drawdown_duration_bars", "Longest drawdown", "int_bars", False,
         "Bars spent below the previous equity peak"),
        ("recovery_factor", "Recovery factor", "ratio", True,
         "Net profit divided by maximum drawdown"),
        ("sharpe_ratio", "Sharpe ratio", "ratio", True,
         "Annualised excess return divided by return volatility"),
        ("sortino_ratio", "Sortino ratio", "ratio", True,
         "Like Sharpe but penalising only downside volatility"),
        ("calmar_ratio", "Calmar ratio", "ratio", True,
         "Annual return divided by maximum drawdown"),
        ("annual_volatility_pct", "Annual volatility", "pct", False, ""),
        ("ulcer_index", "Ulcer index", "ratio", False,
         "Root mean square of the drawdown series"),
        ("sqn", "System quality (SQN)", "ratio", True,
         "sqrt(n) x mean(R) / stdev(R)"),
        ("kelly_fraction", "Kelly fraction", "ratio", False,
         "Theoretical optimal fraction of capital; treat as an upper bound"),
        ("exposure_pct", "Time in market", "pct", False,
         "Percentage of bars with an open position"),
    )),
    ("Costs", (
        ("total_commission", "Commission", "money_cost", False, ""),
        ("total_slippage", "Slippage", "money_cost", False, ""),
        ("total_spread_cost", "Spread", "money_cost", False, ""),
        ("total_costs", "Total costs", "money_cost", False,
         "What the strategy paid to trade"),
    )),
    ("Long / Short", (
        ("long_trades", "Long trades", "int", False, ""),
        ("long_win_rate", "Long win rate", "pct", False, ""),
        ("long_net_profit", "Long net profit", "money", True, ""),
        ("short_trades", "Short trades", "int", False, ""),
        ("short_win_rate", "Short win rate", "pct", False, ""),
        ("short_net_profit", "Short net profit", "money", True, ""),
    )),
    ("Excursion", (
        ("avg_mae", "Average MAE", "points", False,
         "Average worst adverse move while a trade was open, in price points"),
        ("avg_mfe", "Average MFE", "points", False,
         "Average best favourable move while a trade was open, in price points"),
        ("avg_r_multiple", "Average R", "ratio", True, ""),
        ("std_r_multiple", "R standard deviation", "ratio", False, ""),
    )),
)


# ==========================================================================
# Public entry point
# ==========================================================================

def export_html_report(result: BacktestResult, path: str | Path) -> str:
    """Write a complete, self-contained HTML report; returns the path written."""
    target = Path(path)
    document = build_html_report(result)
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(document, encoding="utf-8")
    except OSError as exc:
        raise ReportError(
            f"The report could not be written to {target}. Check that the folder "
            f"exists and that you have permission to write there.",
            detail=f"{type(exc).__name__}: {exc}") from exc
    log.info("Wrote HTML report (%d characters) to %s", len(document), target)
    return str(target)


def build_html_report(result: BacktestResult) -> str:
    """The whole document as a string.  Separated so it can be tested without I/O."""
    ctx = ReportContext(result)
    body = "\n".join((
        _section_header(ctx),
        _section_headline(ctx),
        _section_warnings(ctx),
        _section_charts(ctx),
        _section_metrics(ctx),
        _section_periodic(ctx),
        _section_exits(ctx),
        _section_montecarlo(ctx),
        _section_trades(ctx),
        _section_assumptions(ctx),
    ))
    title = _e(f"{result.strategy_name or 'Backtest'} — "
               f"{result.instrument_symbol or ''} {result.timeframe_label or ''}".strip())
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{title}</title>\n"
        f"<style>\n{_css()}\n</style>\n</head>\n"
        f'<body>\n<div class="page">\n{body}\n</div>\n</body>\n</html>\n'
    )


# ==========================================================================
# The prepared view of a result
# ==========================================================================

class ReportContext:
    """Everything the sections need, computed once.

    The report never trusts a field's units when it can derive the value itself:
    the underwater series is recomputed from equity and its running maximum
    rather than read from ``curves.drawdown_pct``, so a chart cannot silently be
    drawn a hundred times too large.
    """

    def __init__(self, result: BacktestResult) -> None:
        self.result = result
        self.trades: list[Trade] = list(result.trades)
        self.currency = currency_symbol(result)
        self.decimals = price_decimals(result)
        self.timezone = instrument_timezone(result)
        self.metrics = _metrics_with_fallbacks(result)
        self.reliability: dict[str, str] = dict(
            (result.metrics or {}).get("reliability", {}) or {})
        self.reliability_notes: dict[str, str] = dict(
            (result.metrics or {}).get("reliability_notes", {}) or {})

        curves = result.curves
        if curves is not None and len(curves) > 0:
            self.ts = np.asarray(curves.ts, dtype="int64")
            self.equity = np.asarray(curves.equity, dtype="float64")
            self.balance = np.asarray(curves.balance, dtype="float64")
            self.peak = np.maximum.accumulate(np.nan_to_num(
                self.equity, nan=float(result.config.starting_capital)))
            with np.errstate(divide="ignore", invalid="ignore"):
                under = np.where(self.peak > 0.0, self.equity / self.peak - 1.0, 0.0)
            self.underwater = np.nan_to_num(under, nan=0.0) * 100.0
        else:
            self.ts = np.zeros(0, dtype="int64")
            self.equity = np.zeros(0, dtype="float64")
            self.balance = np.zeros(0, dtype="float64")
            self.peak = np.zeros(0, dtype="float64")
            self.underwater = np.zeros(0, dtype="float64")

        self.monthly, self.yearly = _periodic_returns(result, self.ts, self.equity,
                                                      self.timezone)

    # -- formatting ------------------------------------------------------

    def money(self, value: Any) -> str:
        return _money(value, self.currency)

    def fmt(self, value: Any, kind: str) -> str:
        """Format one metric exactly as the statistics panel would."""
        if value is None:
            return "-"
        if isinstance(value, float) and math.isnan(value):
            return "-"
        if kind == "money":
            return self.money(value)
        if kind == "money_cost":
            return self.money(-abs(float(value))) if value else "-"
        if kind == "pct":
            return _pct(value)
        if kind == "int":
            try:
                return f"{int(value):,}"
            except (TypeError, ValueError):
                return str(value)
        if kind == "int_bars":
            try:
                return f"{int(value):,} bars"
            except (TypeError, ValueError):
                return str(value)
        if kind == "float1":
            return _number(value, 1)
        if kind == "ratio":
            if isinstance(value, float) and math.isinf(value):
                return "∞"
            return _number(value, 2)
        if kind == "duration":
            return _duration(value)
        if kind == "points":
            return _number(value, self.decimals)
        return str(value)

    def colour_for(self, key: str, kind: str, value: Any, signed: bool) -> str:
        """The statistics panel's colour rule, so the two agree on sign."""
        if not signed or not isinstance(value, (int, float)) or isinstance(value, bool):
            return PALETTE.text
        v = float(value)
        if v != v:
            return PALETTE.text_muted
        if key in ("max_drawdown", "max_drawdown_pct", "gross_loss",
                   "largest_loss", "avg_loss"):
            return PALETTE.short if v != 0 else PALETTE.text_dim
        if kind == "ratio" and key in ("profit_factor", "recovery_factor", "sharpe_ratio",
                                       "sortino_ratio", "calmar_ratio", "sqn"):
            threshold = 1.0 if key in ("profit_factor", "recovery_factor") else 0.0
            return (PALETTE.long if v > threshold else
                    PALETTE.short if v < threshold else PALETTE.text_dim)
        return PALETTE.long if v > 0 else PALETTE.short if v < 0 else PALETTE.text_dim


# ==========================================================================
# Sections
# ==========================================================================

def _section_header(ctx: ReportContext) -> str:
    rows = "".join(
        f'<div class="meta-item"><span class="meta-label">{_e(label)}</span>'
        f'<span class="meta-value">{_e(value)}</span></div>'
        for label, value in run_header_fields(ctx.result))
    return (
        '<header class="head">'
        f'<div class="head-title">{_e(ctx.result.strategy_name or "Backtest report")}</div>'
        f'<div class="head-sub">{_e(ctx.result.instrument_symbol or "")} '
        f'{_e(ctx.result.timeframe_label or "")} — backtest report</div>'
        f'<div class="meta">{rows}</div>'
        '</header>')


def _section_headline(ctx: ReportContext) -> str:
    m = ctx.metrics
    cards: list[str] = []
    for key, label, kind, signed in (
            ("net_profit", "Net profit", "money", True),
            ("return_pct", "Return", "pct", True),
            ("max_drawdown_pct", "Max drawdown", "pct", True),
            ("profit_factor", "Profit factor", "ratio", True),
            ("total_trades", "Trades", "int", False),
            ("win_rate", "Win rate", "pct", False),
            ("sharpe_ratio", "Sharpe", "ratio", True),
            ("expectancy", "Expectancy", "money", True)):
        value = m.get(key)
        colour = ctx.colour_for(key, kind, value, signed)
        badge = _badge(ctx, key)
        cards.append(
            f'<div class="kpi"><div class="kpi-label">{_e(label)}{badge}</div>'
            f'<div class="kpi-value" style="color:{colour}">'
            f'{_e(ctx.fmt(value, kind))}</div></div>')
    return f'<section class="kpis">{"".join(cards)}</section>'


def _section_warnings(ctx: ReportContext) -> str:
    items: list[str] = []
    n = int(ctx.metrics.get("total_trades", 0) or 0)
    if n == 0:
        items.append("This run produced no trades. Nothing below describes a "
                     "strategy; it describes an idle account.")
    elif n < 30:
        items.append(f"Only {n} trades. Profit factor, win rate, Sharpe and every "
                     f"other ratio here is dominated by noise at this sample size. "
                     f"Metrics the analytics layer could not stand behind are marked "
                     f"LOW n.")
    items.extend(str(w) for w in (ctx.result.warnings or ()))
    if not items:
        return ""
    body = "".join(f"<li>{_e(text)}</li>" for text in items)
    return ('<section class="card warn"><h2>Warnings</h2>'
            f'<ul class="warn-list">{body}</ul></section>')


def _section_charts(ctx: ReportContext) -> str:
    if len(ctx.equity) == 0:
        return ('<section class="card"><h2>Equity</h2>'
                '<p class="empty">This run has no equity curve.</p></section>')
    equity_svg = _equity_chart(ctx)
    under_svg = _underwater_chart(ctx)
    trades_svg = _trade_strip(ctx)
    return (
        '<section class="card"><h2>Equity curve</h2>'
        '<p class="lede">Equity is the account balance plus the open position marked '
        'to market. The shaded band is the distance below the previous equity peak: '
        'the wider it is, the longer the strategy spent giving money back.</p>'
        f'{equity_svg}'
        f'<div class="legend">{_legend_item(PALETTE.equity, "Equity")}'
        f'{_legend_item(PALETTE.balance, "Closed balance")}'
        f'{_legend_item(PALETTE.drawdown, "Below peak")}</div>'
        '</section>'
        '<section class="card"><h2>Drawdown</h2>'
        '<p class="lede">Percent below the previous equity high, bar by bar. Time '
        'spent under water is what a live trader actually experiences.</p>'
        f'{under_svg}</section>'
        '<section class="card"><h2>Profit and loss per trade</h2>'
        '<p class="lede">Every closed trade in order, in cash after costs. A single '
        'bar taller than the rest is a result that depends on one trade.</p>'
        f'{trades_svg}</section>')


def _section_metrics(ctx: ReportContext) -> str:
    blocks: list[str] = []
    for title, entries in METRIC_GROUPS:
        rows: list[str] = []
        for key, label, kind, signed, explanation in entries:
            value = ctx.metrics.get(key)
            colour = ctx.colour_for(key, kind, value, signed)
            state = ctx.reliability.get(key, "ok")
            if state == "unavailable":
                colour = PALETTE.text_muted
            note = ctx.reliability_notes.get(key, "") or explanation
            rows.append(
                f'<tr{_title_attr(note)}><th scope="row">{_e(label)}'
                f'{_badge(ctx, key)}</th>'
                f'<td class="num" style="color:{colour}">{_e(ctx.fmt(value, kind))}</td></tr>')
        blocks.append(f'<div class="metric-group"><h3>{_e(title)}</h3>'
                      f'<table class="metrics">{"".join(rows)}</table></div>')
    legend = (
        f'<p class="lede">A <span class="badge low">LOW n</span> badge means the '
        f'sample behind that number is too small to trust it; '
        f'<span class="badge na">N/A</span> means it could not be computed at all, '
        f'usually because its denominator was zero.</p>')
    return ('<section class="card"><h2>Performance statistics</h2>'
            f'{legend}<div class="metric-grid">{"".join(blocks)}</div></section>')


def _section_periodic(ctx: ReportContext) -> str:
    if not ctx.monthly:
        return ""
    heat = _monthly_heatmap(ctx)
    month_table = _monthly_table(ctx)
    year_table = _yearly_table(ctx)
    return ('<section class="card"><h2>Returns by month</h2>'
            '<p class="lede">Each cell is the change in account equity over that '
            'calendar month, measured in the instrument timezone '
            f'({_e(ctx.timezone)}). Months are compounding percentages, not sums of '
            'trade P&amp;L.</p>'
            f'{heat}{month_table}<h3 class="sub">By year</h3>{year_table}</section>')


def _section_exits(ctx: ReportContext) -> str:
    if not ctx.trades:
        return ""
    groups: dict[str, list[Trade]] = {}
    for t in ctx.trades:
        groups.setdefault(t.exit_reason.label, []).append(t)
    total = float(sum(t.net_pnl for t in ctx.trades))
    rows: list[str] = []
    for label, trades in sorted(groups.items(),
                                key=lambda kv: -abs(sum(t.net_pnl for t in kv[1]))):
        net = float(sum(t.net_pnl for t in trades))
        wins = sum(1 for t in trades if t.net_pnl > 0)
        share = len(trades) / len(ctx.trades) * 100.0
        rows.append(
            f"<tr><td>{_e(label)}</td>"
            f'<td class="num">{len(trades):,}</td>'
            f'<td class="num">{_e(_pct(share))}</td>'
            f'<td class="num" style="color:{_sign_colour(net)}">{_e(ctx.money(net))}</td>'
            f'<td class="num">{_e(_pct(wins / len(trades) * 100.0))}</td>'
            f'<td class="num" style="color:{_sign_colour(net)}">'
            f'{_e(ctx.money(net / len(trades)))}</td></tr>')
    rows.append(
        f'<tr class="total"><td>All exits</td><td class="num">{len(ctx.trades):,}</td>'
        f'<td class="num">100.00%</td>'
        f'<td class="num" style="color:{_sign_colour(total)}">{_e(ctx.money(total))}</td>'
        f'<td class="num">'
        f'{_e(_pct(sum(1 for t in ctx.trades if t.net_pnl > 0) / len(ctx.trades) * 100.0))}'
        f'</td><td class="num" style="color:{_sign_colour(total)}">'
        f'{_e(ctx.money(total / len(ctx.trades)))}</td></tr>')
    return ('<section class="card"><h2>Where the money came from</h2>'
            '<p class="lede">Net profit split by the reason each position was closed. '
            'A strategy whose profit arrives at the time stop rather than the target '
            'is a directional bet, whatever its barriers say.</p>'
            '<div class="scroll"><table class="grid"><thead><tr>'
            '<th>Exit reason</th><th class="num">Trades</th><th class="num">Share</th>'
            '<th class="num">Net P&amp;L</th><th class="num">Win rate</th>'
            f'<th class="num">Average</th></tr></thead><tbody>{"".join(rows)}</tbody>'
            '</table></div></section>')


#: Draws for the report's own resampling. Enough for a stable 5th and 95th
#: percentile and still a few hundredths of a second on a normal trade list.
_REPORT_DRAWS = 4000


def _section_montecarlo(ctx: ReportContext) -> str:
    """What else this trade sequence could have done.

    The report is the artefact that gets shared, and a single equity curve
    shared on its own reads as the outcome rather than as one draw from a
    distribution. The block bootstrap is the default here for the same reason
    it is in the dialog: trades cluster by regime, and drawing them
    independently reports a gentler drawdown than the strategy will produce.

    Never fatal: a report that cannot be written because a resampling failed
    would be a worse outcome than a report without this section.
    """
    if len(ctx.trades) < 2:
        return ""
    try:
        from ..analytics.montecarlo import resample_result

        mc = resample_result(ctx.result, method="block", draws=_REPORT_DRAWS)
    except Exception:                       # noqa: BLE001 - see the docstring
        log.debug("Monte Carlo section skipped", exc_info=True)
        return ""

    quantiles = (5, 25, 50, 75, 95)
    rows_by_name = (
        ("Final equity", mc.percentiles(mc.final_equity, quantiles), ctx.money),
        ("Worst drawdown", mc.percentiles(mc.max_drawdown, quantiles), ctx.money),
        ("Worst drawdown %",
         mc.percentiles(mc.max_drawdown_pct, quantiles), _pct),
        ("Trades under water",
         mc.percentiles(mc.longest_drawdown.astype(float), quantiles),
         lambda v: f"{v:,.0f}"),
    )
    rows = []
    for label, values, render in rows_by_name:
        cells = "".join(f'<td class="num">{_e(render(values[q]))}</td>'
                        for q in quantiles)
        rows.append(f"<tr><td>{_e(label)}</td>{cells}</tr>")

    observed = (
        f'<tr class="total"><td>This backtest</td>'
        f'<td class="num" colspan="2">{_e(ctx.money(mc.observed.final_equity))}</td>'
        f'<td class="num" colspan="3">'
        f'{_e(ctx.money(mc.observed.max_drawdown))} drawdown '
        f'({_e(_pct(mc.observed.max_drawdown_pct))})</td></tr>')

    headers = "".join(f'<th class="num">{q}th</th>' for q in quantiles)
    worst = mc.drawdown_at(95)
    summary = (
        f"{_e(f'{mc.losing_probability * 100:.1f}')}% of resampled runs lost "
        f"money and {_e(f'{mc.ruin_probability * 100:.1f}')}% closed below "
        f"{_e(ctx.money(mc.ruin_level))} at some point. "
        f"One run in twenty had a drawdown worse than "
        f"{_e(ctx.money(worst))} — that is the number to size an account "
        f"against, not the {_e(ctx.money(mc.observed.max_drawdown))} this "
        f"backtest happened to produce.")
    return (
        '<section class="card"><h2>What else could have happened</h2>'
        f'<p class="lede">{_REPORT_DRAWS:,} resampled runs over these '
        f'{len(ctx.trades):,} trades, drawn in contiguous blocks of '
        f'{mc.block_size} so that losing streaks survive the resampling. '
        'This describes the range of paths <em>these trades</em> could have '
        'produced. It cannot tell you whether the strategy has an edge: if '
        'these trades came from a rule fitted to this data, every draw is '
        'fitted to it too.</p>'
        '<div class="scroll"><table class="grid"><thead><tr>'
        f'<th>Percentile</th>{headers}</tr></thead>'
        f'<tbody>{"".join(rows)}{observed}</tbody></table></div>'
        f'<p class="lede">{summary}</p></section>')


def _section_trades(ctx: ReportContext) -> str:
    if not ctx.trades:
        return ('<section class="card"><h2>Trades</h2>'
                '<p class="empty">This run closed no trades.</p></section>')
    from .csv_export import iso_timestamps

    shown = ctx.trades[:MAX_TRADE_ROWS]
    entry_utc, entry_local = iso_timestamps([t.entry_ts for t in shown], ctx.timezone)
    exit_utc, exit_local = iso_timestamps([t.exit_ts for t in shown], ctx.timezone)
    del entry_utc, exit_utc  # the local reading is what a trader recognises

    d = ctx.decimals
    rows: list[str] = []
    for i, t in enumerate(shown):
        costs = float(t.commission) + float(t.slippage_cost) + float(t.spread_cost)
        r = "-" if t.r_multiple is None or t.r_multiple != t.r_multiple \
            else f"{float(t.r_multiple):+.2f}"
        side_colour = PALETTE.long if t.side.value == "long" else PALETTE.short
        rows.append(
            f'<tr><td class="num dim">{i + 1}</td>'
            f'<td class="mono">{_e(entry_local[i][:16].replace("T", " "))}</td>'
            f'<td class="mono">{_e(exit_local[i][:16].replace("T", " "))}</td>'
            f'<td style="color:{side_colour}">{_e(t.side.value.upper())}</td>'
            f'<td class="num">{_e(_qty(t.quantity))}</td>'
            f'<td class="num">{_e(_price(t.entry_price, d))}</td>'
            f'<td class="num">{_e(_price(t.exit_price, d))}</td>'
            f'<td class="num dim">{_e(_price(t.stop_loss, d))}</td>'
            f'<td class="num dim">{_e(_price(t.take_profit, d))}</td>'
            f'<td class="num dim">{_e(ctx.money(-abs(costs)) if costs else "-")}</td>'
            f'<td class="num" style="color:{_sign_colour(t.net_pnl)}">'
            f'{_e(ctx.money(t.net_pnl))}</td>'
            f'<td class="num" style="color:{_sign_colour(t.return_pct)}">'
            f'{_e(_pct(t.return_pct, 2, signed=True))}</td>'
            f'<td class="num">{_e(r)}</td>'
            f'<td class="num dim">{int(t.bars_held):,}</td>'
            f'<td class="num dim">{_e(_duration(t.duration_seconds))}</td>'
            f'<td class="num dim">{_e(_number(t.mae, d))}</td>'
            f'<td class="num dim">{_e(_number(t.mfe, d))}</td>'
            f'<td>{_e(t.exit_reason.label)}</td>'
            f'<td class="num dim">{_e(ctx.money(t.equity_after))}</td></tr>')

    truncated = ""
    if len(ctx.trades) > MAX_TRADE_ROWS:
        truncated = (f'<p class="note">Showing the first {MAX_TRADE_ROWS:,} of '
                     f'{len(ctx.trades):,} trades. Export the trades to CSV for the '
                     f'complete list — nothing is summarised away there.</p>')
    header = ("<tr><th>#</th><th>Entry</th><th>Exit</th><th>Side</th>"
              '<th class="num">Qty</th><th class="num">Entry px</th>'
              '<th class="num">Exit px</th><th class="num">Stop</th>'
              '<th class="num">Target</th><th class="num">Costs</th>'
              '<th class="num">Net P&amp;L</th><th class="num">Return</th>'
              '<th class="num">R</th><th class="num">Bars</th>'
              '<th class="num">Held</th><th class="num">MAE</th>'
              '<th class="num">MFE</th><th>Exit reason</th>'
              '<th class="num">Equity</th></tr>')
    return ('<section class="card"><h2>Trades</h2>'
            f'<p class="lede">Times are shown in {_e(ctx.timezone)}. Costs are the '
            'commission, spread and slippage charged to that trade; net P&amp;L already '
            'has them deducted.</p>'
            f'{truncated}'
            f'<div class="scroll"><table class="grid trades"><thead>{header}</thead>'
            f'<tbody>{"".join(rows)}</tbody></table></div></section>')


def _section_assumptions(ctx: ReportContext) -> str:
    cfg = ctx.result.config
    ex = cfg.execution
    risk = cfg.risk
    session = cfg.session
    exits = cfg.exits

    if ex.signal_execution is SignalExecution.NEXT_OPEN:
        timing = ("A rule was evaluated on the close of a bar and the resulting order "
                  "filled at the open of the <em>next</em> bar. Nothing in this run "
                  "traded at a price that was not yet knowable when the decision was "
                  "made.")
    else:
        timing = ("Orders filled at the close of the same bar that produced the "
                  "signal. That price was only known once the bar had finished, so "
                  "this setting flatters the result; treat every number in this "
                  "report as an upper bound.")

    priority = {
        "pessimistic": ("When one bar's range covered both the stop and the target, "
                        "the stop was taken. Bar data cannot say which price came "
                        "first, and this is the only assumption that will not "
                        "flatter the result."),
        "optimistic": ("When one bar's range covered both the stop and the target, "
                       "the target was taken. Bar data cannot say which came first, "
                       "and this assumption is the generous one: expect live results "
                       "to be worse."),
        "ohlc_path": ("When one bar's range covered both the stop and the target, an "
                      "open-high-low-close path was assumed — high first on an up "
                      "bar, low first on a down bar — and whichever barrier that "
                      "path reached first was taken. It is a guess about intrabar "
                      "order, not a measurement."),
    }[ex.intrabar_priority.value]

    sizing = _describe_sizing(risk)

    session_text = ("No session filter: every bar in the data was tradeable."
                    if not session.enabled else
                    f"Trading was restricted to {_e(session.start)}–{_e(session.end)} "
                    f"{_e(session.timezone)} on "
                    f"{_e(_weekday_names(session.weekdays))}"
                    + (", and any position still open on the last in-session bar of "
                       "the day was closed there." if session.flat_at_session_end
                       else ", and positions were allowed to carry across the "
                            "session boundary."))

    if risk.max_daily_loss > 0:
        unit = "percent of equity" if risk.max_daily_loss_is_percent else "in cash"
        daily = (f"Trading stopped for the rest of the session day once the day's "
                 f"realised loss reached {risk.max_daily_loss:g} {unit}; any open "
                 f"position was closed at that point and no new position was opened "
                 f"until the next day.")
    else:
        daily = "No daily loss limit was applied."

    if exits.partial_exits:
        pieces = ", ".join(f"{frac * 100:g}% at {r:g}R" for frac, r in exits.partial_exits)
        partial = (f"Partial exits were used ({pieces}). Each piece is reported as its "
                   f"own trade row with its own entry price, exit price and P&amp;L, "
                   f"linked back to the original position by a parent trade id in the "
                   f"CSV export, so the trade count here is larger than the number of "
                   f"positions actually opened.")
    else:
        partial = "No partial exits: every position was closed in one piece."

    paragraphs = [
        ("Order timing", timing),
        ("Intrabar barriers", priority),
        ("Gaps", "If a bar opened beyond a resting stop or target, the fill was taken "
                 "at that opening price and not at the barrier price. A stop does not "
                 "protect you from a gap and this simulation does not pretend it does."),
        ("Costs", f"{_e(_sentence(describe_cost_model(cfg.costs)))}. Every one of "
                  f"these is charged against the trade; there is no setting in which "
                  f"transacting pays the account."),
        ("Position sizing", sizing),
        ("Session", session_text),
        ("Daily loss limit", daily),
        ("Partial exits", partial),
    ]
    body = "".join(f'<div class="assume"><h3>{_e(title)}</h3><p>{text}</p></div>'
                   for title, text in paragraphs)

    limits = (
        "<p>What this simulation cannot model, at all: your position in the order "
        "queue, partial fills, the latency between your machine and the exchange, "
        "how much size the book would really have absorbed, the impact your own "
        "order would have had on the price, and whether the instrument could have "
        "been shorted at that moment. It assumes every order you sent was filled in "
        "full at a price derived from a bar that has already happened.</p>"
        "<p>And it cannot model you. The result above is one path through one "
        "sample of history, chosen by a person who could see that history. If this "
        "configuration is the best of many that were tried, the number that matters "
        "is not the profit — it is how many were tried. See the Backtesting "
        "Assumptions document in Help for the full account.</p>")

    return ('<section class="card"><h2>How this was simulated</h2>'
            f'<div class="assume-grid">{body}</div>'
            f'<div class="limits"><h3>Limits</h3>{limits}</div></section>')


# ==========================================================================
# Charts — every one of these is hand-drawn SVG
# ==========================================================================

def _equity_chart(ctx: ReportContext) -> str:
    w, h = 1000.0, 320.0
    left, right, top, bottom = 78.0, 14.0, 14.0, 30.0
    pw, ph = w - left - right, h - top - bottom
    n = len(ctx.equity)

    idx = decimate_indices(ctx.equity, _CHART_POINTS)
    lo = float(np.nanmin(np.minimum(ctx.equity, ctx.balance)))
    hi = float(np.nanmax(ctx.peak))
    start = float(ctx.result.config.starting_capital)
    lo, hi = min(lo, start), max(hi, start)
    lo, hi = _pad_range(lo, hi)

    def sx(i: int | float) -> float:
        return left + (pw * (float(i) / max(1, n - 1)))

    def sy(v: float) -> float:
        return top + ph * (hi - float(v)) / (hi - lo)

    parts: list[str] = [f'<svg class="chart" viewBox="0 0 {w:g} {h:g}" '
                        f'preserveAspectRatio="none" role="img" '
                        f'aria-label="Equity curve">']
    parts.append(f'<rect x="{left:g}" y="{top:g}" width="{pw:g}" height="{ph:g}" '
                 f'fill="{PALETTE.panel_bg}"/>')
    for value in _ticks(lo, hi, 5):
        y = sy(value)
        parts.append(f'<line x1="{left:g}" y1="{y:.1f}" x2="{left + pw:g}" y2="{y:.1f}" '
                     f'stroke="{PALETTE.grid}" stroke-width="1"/>')
        parts.append(f'<text x="{left - 6:g}" y="{y + 3.5:.1f}" text-anchor="end" '
                     f'class="axis">{_e(_money(value, ctx.currency, 0))}</text>')

    # The band between the running peak and equity: the drawdown, shaded.
    peak_pts = [(sx(i), sy(ctx.peak[i])) for i in idx]
    eq_pts = [(sx(i), sy(ctx.equity[i])) for i in idx]
    band = ("M " + " L ".join(f"{x:.1f},{y:.1f}" for x, y in peak_pts)
            + " L " + " L ".join(f"{x:.1f},{y:.1f}" for x, y in reversed(eq_pts)) + " Z")
    parts.append(f'<path d="{band}" fill="{_rgba(PALETTE.drawdown, 0.22)}" '
                 f'stroke="none"/>')

    y_start = sy(start)
    parts.append(f'<line x1="{left:g}" y1="{y_start:.1f}" x2="{left + pw:g}" '
                 f'y2="{y_start:.1f}" stroke="{PALETTE.border_strong}" '
                 f'stroke-width="1" stroke-dasharray="4 4"/>')
    parts.append(f'<path d="{_polyline([(sx(i), sy(ctx.balance[i])) for i in idx])}" '
                 f'fill="none" stroke="{PALETTE.balance}" stroke-width="1.2" '
                 f'stroke-dasharray="3 3" opacity="0.85"/>')
    parts.append(f'<path d="{_polyline(eq_pts)}" fill="none" '
                 f'stroke="{PALETTE.equity}" stroke-width="1.8" '
                 f'stroke-linejoin="round"/>')
    parts.extend(_x_axis(ctx, left, pw, top + ph, n))
    parts.append("</svg>")
    return "".join(parts)


def _underwater_chart(ctx: ReportContext) -> str:
    w, h = 1000.0, 170.0
    left, right, top, bottom = 78.0, 14.0, 12.0, 30.0
    pw, ph = w - left - right, h - top - bottom
    n = len(ctx.underwater)
    idx = decimate_indices(ctx.underwater, _CHART_POINTS)
    worst = float(np.nanmin(ctx.underwater)) if n else 0.0
    lo = min(worst, -0.5) * 1.08
    hi = 0.0

    def sx(i: int | float) -> float:
        return left + pw * (float(i) / max(1, n - 1))

    def sy(v: float) -> float:
        return top + ph * (hi - float(v)) / (hi - lo)

    parts = [f'<svg class="chart" viewBox="0 0 {w:g} {h:g}" preserveAspectRatio="none" '
             f'role="img" aria-label="Drawdown under water">']
    parts.append(f'<rect x="{left:g}" y="{top:g}" width="{pw:g}" height="{ph:g}" '
                 f'fill="{PALETTE.panel_bg}"/>')
    for value in _ticks(lo, hi, 4):
        y = sy(value)
        parts.append(f'<line x1="{left:g}" y1="{y:.1f}" x2="{left + pw:g}" y2="{y:.1f}" '
                     f'stroke="{PALETTE.grid}" stroke-width="1"/>')
        parts.append(f'<text x="{left - 6:g}" y="{y + 3.5:.1f}" text-anchor="end" '
                     f'class="axis">{_e(_pct(value, 1))}</text>')
    pts = [(sx(i), sy(ctx.underwater[i])) for i in idx]
    area = (f"M {sx(idx[0]):.1f},{sy(0.0):.1f} L "
            + " L ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
            + f" L {sx(idx[-1]):.1f},{sy(0.0):.1f} Z")
    parts.append(f'<path d="{area}" fill="{_rgba(PALETTE.drawdown, 0.35)}"/>')
    parts.append(f'<path d="{_polyline(pts)}" fill="none" stroke="{PALETTE.drawdown}" '
                 f'stroke-width="1.3"/>')
    parts.extend(_x_axis(ctx, left, pw, top + ph, n))
    parts.append("</svg>")
    return "".join(parts)


def _trade_strip(ctx: ReportContext) -> str:
    if not ctx.trades:
        return '<p class="empty">No trades to plot.</p>'
    w, h = 1000.0, 180.0
    left, right, top, bottom = 78.0, 14.0, 12.0, 22.0
    pw, ph = w - left - right, h - top - bottom
    pnl = np.array([float(t.net_pnl) for t in ctx.trades], dtype="float64")
    n = len(pnl)
    span = float(np.nanmax(np.abs(pnl))) if n else 1.0
    span = span if span > 0 else 1.0
    mid = top + ph / 2.0
    bar_w = max(0.6, pw / max(1, n) * 0.9)

    parts = [f'<svg class="chart" viewBox="0 0 {w:g} {h:g}" preserveAspectRatio="none" '
             f'role="img" aria-label="Profit and loss per trade">']
    parts.append(f'<rect x="{left:g}" y="{top:g}" width="{pw:g}" height="{ph:g}" '
                 f'fill="{PALETTE.panel_bg}"/>')
    for frac, value in ((1.0, span), (0.0, 0.0), (-1.0, -span)):
        y = mid - frac * (ph / 2.0 - 4.0)
        parts.append(f'<line x1="{left:g}" y1="{y:.1f}" x2="{left + pw:g}" y2="{y:.1f}" '
                     f'stroke="{PALETTE.grid if frac else PALETTE.border_strong}" '
                     f'stroke-width="1"/>')
        parts.append(f'<text x="{left - 6:g}" y="{y + 3.5:.1f}" text-anchor="end" '
                     f'class="axis">{_e(_money(value, ctx.currency, 0))}</text>')
    for i, v in enumerate(pnl):
        x = left + pw * (i / max(1, n)) + (pw / max(1, n) - bar_w) / 2.0
        height = abs(v) / span * (ph / 2.0 - 4.0)
        y = mid - height if v >= 0 else mid
        colour = PALETTE.long if v > 0 else PALETTE.short if v < 0 else PALETTE.text_muted
        parts.append(f'<rect x="{x:.2f}" y="{y:.2f}" width="{bar_w:.2f}" '
                     f'height="{max(0.6, height):.2f}" fill="{colour}" opacity="0.9"/>')
    parts.append(f'<text x="{left:g}" y="{h - 6:g}" class="axis">trade 1</text>')
    parts.append(f'<text x="{left + pw:g}" y="{h - 6:g}" text-anchor="end" '
                 f'class="axis">trade {n:,}</text>')
    parts.append("</svg>")
    return "".join(parts)


def _monthly_heatmap(ctx: ReportContext) -> str:
    years = sorted({y for y, _m in ctx.monthly})
    cell, gap = 68.0, 3.0
    label_w, head_h = 54.0, 18.0
    w = label_w + 12 * (cell + gap)
    h = head_h + len(years) * (26.0 + gap) + 4.0
    values = [v for v in ctx.monthly.values() if v == v]
    scale = max((abs(v) for v in values), default=1.0) or 1.0

    parts = [f'<svg class="heat" viewBox="0 0 {w:.0f} {h:.0f}" role="img" '
             f'aria-label="Monthly returns heat map">']
    for c, name in enumerate(_MONTHS):
        x = label_w + c * (cell + gap) + cell / 2.0
        parts.append(f'<text x="{x:.1f}" y="{head_h - 6:.1f}" text-anchor="middle" '
                     f'class="axis">{name}</text>')
    for r, year in enumerate(years):
        y = head_h + r * (26.0 + gap)
        parts.append(f'<text x="{label_w - 8:.1f}" y="{y + 17:.1f}" text-anchor="end" '
                     f'class="axis strong">{year}</text>')
        for c in range(12):
            value = ctx.monthly.get((year, c + 1))
            x = label_w + c * (cell + gap)
            if value is None or value != value:
                parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{cell:g}" '
                             f'height="26" rx="3" fill="{PALETTE.panel_bg}" '
                             f'stroke="{PALETTE.border}"/>')
                continue
            strength = min(1.0, abs(value) / scale)
            base = PALETTE.long if value >= 0 else PALETTE.short
            parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{cell:g}" height="26" '
                         f'rx="3" fill="{_rgba(base, 0.15 + 0.65 * strength)}" '
                         f'stroke="{PALETTE.border}"/>')
            parts.append(f'<text x="{x + cell / 2:.1f}" y="{y + 17:.1f}" '
                         f'text-anchor="middle" class="cellv">'
                         f'{_e(_pct(value, 1, signed=True))}</text>')
    parts.append("</svg>")
    return f'<div class="scroll">{"".join(parts)}</div>'


def _monthly_table(ctx: ReportContext) -> str:
    years = sorted({y for y, _m in ctx.monthly})
    head = ("<tr><th>Year</th>"
            + "".join(f'<th class="num">{m}</th>' for m in _MONTHS)
            + '<th class="num">Year</th></tr>')
    rows: list[str] = []
    for year in years:
        cells: list[str] = []
        for month in range(1, 13):
            value = ctx.monthly.get((year, month))
            if value is None or value != value:
                cells.append('<td class="num dim">-</td>')
            else:
                cells.append(f'<td class="num" style="color:{_sign_colour(value)}">'
                             f'{_e(_pct(value, 2, signed=True))}</td>')
        total = ctx.yearly.get(year, {}).get("return_pct")
        total_cell = ('<td class="num dim">-</td>' if total is None or total != total
                      else f'<td class="num strong" style="color:{_sign_colour(total)}">'
                           f'{_e(_pct(total, 2, signed=True))}</td>')
        rows.append(f'<tr><th scope="row">{year}</th>{"".join(cells)}{total_cell}</tr>')
    return (f'<div class="scroll"><table class="grid"><thead>{head}</thead>'
            f'<tbody>{"".join(rows)}</tbody></table></div>')


def _yearly_table(ctx: ReportContext) -> str:
    head = ('<tr><th>Year</th><th class="num">Return</th><th class="num">Net P&amp;L</th>'
            '<th class="num">Trades</th><th class="num">Win rate</th>'
            '<th class="num">Best month</th><th class="num">Worst month</th></tr>')
    rows: list[str] = []
    for year in sorted(ctx.yearly):
        info = ctx.yearly[year]
        ret = info.get("return_pct")
        net = info.get("net_pnl")
        rows.append(
            f'<tr><th scope="row">{year}</th>'
            f'<td class="num" style="color:{_sign_colour(ret)}">'
            f'{_e(_pct(ret, 2, signed=True)) if ret is not None else "-"}</td>'
            f'<td class="num" style="color:{_sign_colour(net)}">'
            f'{_e(ctx.money(net)) if net is not None else "-"}</td>'
            f'<td class="num">{int(info.get("trades", 0)):,}</td>'
            f'<td class="num">{_e(_pct(info["win_rate"])) if info.get("trades") else "-"}'
            f'</td>'
            f'<td class="num" style="color:{PALETTE.long}">'
            f'{_e(_pct(info["best_month"], 2, signed=True))}</td>'
            f'<td class="num" style="color:{PALETTE.short}">'
            f'{_e(_pct(info["worst_month"], 2, signed=True))}</td></tr>')
    return (f'<div class="scroll"><table class="grid"><thead>{head}</thead>'
            f'<tbody>{"".join(rows)}</tbody></table></div>')


def _x_axis(ctx: ReportContext, left: float, pw: float, baseline: float, n: int) -> list[str]:
    """Five date labels along the bottom of a time chart."""
    import pandas as pd

    out = [f'<line x1="{left:g}" y1="{baseline:g}" x2="{left + pw:g}" y2="{baseline:g}" '
           f'stroke="{PALETTE.border_strong}" stroke-width="1"/>']
    if n == 0 or len(ctx.ts) == 0:
        return out
    span_days = (int(ctx.ts[-1]) - int(ctx.ts[0])) / 86_400e9
    fmt = "%Y-%m-%d" if span_days > 5 else "%m-%d %H:%M"
    for k in range(5):
        i = int(round((n - 1) * k / 4))
        stamp = pd.Timestamp(int(ctx.ts[min(i, len(ctx.ts) - 1)]), tz="UTC")
        try:
            stamp = stamp.tz_convert(ctx.timezone)
        except Exception:
            pass
        x = left + pw * (i / max(1, n - 1))
        anchor = "start" if k == 0 else "end" if k == 4 else "middle"
        out.append(f'<text x="{x:.1f}" y="{baseline + 15:.1f}" text-anchor="{anchor}" '
                   f'class="axis">{_e(stamp.strftime(fmt))}</text>')
    return out


# ==========================================================================
# Numeric helpers
# ==========================================================================

def _metrics_with_fallbacks(result: BacktestResult) -> dict[str, Any]:
    """The run's metrics, with the basics filled in when analytics did not run.

    A :class:`BacktestResult` assembled by hand -- by a test, or by a caller that
    only wanted the trade list -- still deserves an honest report rather than a
    page of dashes, so the handful of metrics that follow unambiguously from the
    trades and the equity curve are derived here.  Anything the analytics layer
    did provide always wins.
    """
    metrics: dict[str, Any] = {}
    trades = list(result.trades)
    start = float(result.config.starting_capital)
    net = [float(t.net_pnl) for t in trades]
    wins = [v for v in net if v > 0]
    losses = [v for v in net if v < 0]
    gross_profit = float(sum(wins))
    gross_loss = float(sum(losses))

    metrics["total_trades"] = len(trades)
    metrics["winning_trades"] = len(wins)
    metrics["losing_trades"] = len(losses)
    metrics["win_rate"] = (len(wins) / len(trades) * 100.0) if trades else None
    metrics["gross_profit"] = gross_profit
    metrics["gross_loss"] = gross_loss
    metrics["profit_factor"] = (gross_profit / abs(gross_loss) if gross_loss
                                else (float("inf") if gross_profit > 0 else None))
    metrics["starting_balance"] = start
    metrics["ending_balance"] = result.final_equity
    metrics["net_profit"] = result.net_profit
    metrics["return_pct"] = (result.net_profit / start * 100.0) if start else None
    metrics["expectancy"] = (sum(net) / len(net)) if net else None
    metrics["avg_trade"] = metrics["expectancy"]
    metrics["avg_win"] = (gross_profit / len(wins)) if wins else None
    metrics["avg_loss"] = (gross_loss / len(losses)) if losses else None
    metrics["largest_win"] = max(net) if net else None
    metrics["largest_loss"] = min(net) if net else None
    metrics["total_commission"] = float(sum(t.commission for t in trades))
    metrics["total_slippage"] = float(sum(t.slippage_cost for t in trades))
    metrics["total_spread_cost"] = float(sum(t.spread_cost for t in trades))
    metrics["total_costs"] = (metrics["total_commission"] + metrics["total_slippage"]
                              + metrics["total_spread_cost"])
    metrics["long_trades"] = sum(1 for t in trades if t.side.value == "long")
    metrics["short_trades"] = sum(1 for t in trades if t.side.value == "short")

    curves = result.curves
    if curves is not None and len(curves) > 0:
        equity = np.asarray(curves.equity, dtype="float64")
        peak = np.maximum.accumulate(np.nan_to_num(equity, nan=start))
        dd = equity - peak
        with np.errstate(divide="ignore", invalid="ignore"):
            dd_pct = np.where(peak > 0, dd / peak * 100.0, 0.0)
        metrics["max_drawdown"] = float(np.nanmin(dd))
        metrics["max_drawdown_pct"] = float(np.nanmin(dd_pct))

    supplied = dict(result.metrics or {})
    supplied.pop("reliability", None)
    supplied.pop("reliability_notes", None)
    for key, value in supplied.items():
        if not isinstance(value, dict):
            metrics[key] = value
    return metrics


def _periodic_returns(result: BacktestResult, ts: np.ndarray, equity: np.ndarray,
                      tz: str) -> tuple[dict[tuple[int, int], float],
                                        dict[int, dict[str, Any]]]:
    """Calendar-month and calendar-year equity returns, in the instrument's zone.

    Computed here from the equity curve rather than taken from the analytics
    layer because the report needs one specific shape -- a compounding percentage
    per calendar month -- and because a report should be reproducible from the
    result object alone.
    """
    if len(ts) == 0 or len(equity) == 0:
        return {}, {}
    import pandas as pd

    idx = pd.DatetimeIndex(pd.to_datetime(np.asarray(ts, dtype="int64"), utc=True))
    try:
        idx = idx.tz_convert(tz)
    except Exception:
        pass
    series = pd.Series(np.asarray(equity, dtype="float64"), index=idx)
    start = float(result.config.starting_capital)

    monthly: dict[tuple[int, int], float] = {}
    month_end = series.resample("ME").last().dropna()
    previous = start
    for stamp, value in month_end.items():
        monthly[(int(stamp.year), int(stamp.month))] = (
            (float(value) / previous - 1.0) * 100.0 if previous > 0 else float("nan"))
        previous = float(value)

    trade_year: dict[int, list[float]] = {}
    for trade in result.trades:
        stamp = pd.Timestamp(int(trade.exit_ts), tz="UTC")
        try:
            stamp = stamp.tz_convert(tz)
        except Exception:
            pass
        trade_year.setdefault(int(stamp.year), []).append(float(trade.net_pnl))

    yearly: dict[int, dict[str, Any]] = {}
    year_end = series.resample("YE").last().dropna()
    previous = start
    for stamp, value in year_end.items():
        year = int(stamp.year)
        months = [v for (y, _m), v in monthly.items() if y == year and v == v]
        pnl = trade_year.get(year, [])
        yearly[year] = {
            "return_pct": ((float(value) / previous - 1.0) * 100.0
                           if previous > 0 else float("nan")),
            "net_pnl": float(value) - previous,
            "trades": len(pnl),
            "win_rate": (sum(1 for v in pnl if v > 0) / len(pnl) * 100.0) if pnl else 0.0,
            "best_month": max(months) if months else float("nan"),
            "worst_month": min(months) if months else float("nan"),
        }
        previous = float(value)
    return monthly, yearly


def decimate_indices(values: np.ndarray, budget: int) -> list[int]:
    """Indices that keep a curve's shape, including every local extreme.

    A million-bar equity curve cannot go into an SVG point by point, and plain
    stride sampling drops exactly the spikes a reader is looking for, so each
    bucket contributes its minimum and its maximum.
    """
    values = np.nan_to_num(np.asarray(values, dtype="float64"), nan=0.0,
                           posinf=0.0, neginf=0.0)
    n = len(values)
    if n <= budget:
        return list(range(n))
    buckets = max(2, budget // 2)
    edges = np.linspace(0, n, buckets + 1).astype(int)
    keep: set[int] = {0, n - 1}
    for a, b in zip(edges[:-1], edges[1:]):
        if b <= a:
            continue
        segment = values[a:b]
        keep.add(a + int(np.argmin(segment)))
        keep.add(a + int(np.argmax(segment)))
    return sorted(keep)


def _polyline(points: Sequence[tuple[float, float]]) -> str:
    return "M " + " L ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def _pad_range(lo: float, hi: float) -> tuple[float, float]:
    if not math.isfinite(lo) or not math.isfinite(hi):
        return 0.0, 1.0
    if hi - lo < 1e-9:
        pad = max(1.0, abs(hi) * 0.01)
        return lo - pad, hi + pad
    pad = (hi - lo) * 0.06
    return lo - pad, hi + pad


def _ticks(lo: float, hi: float, count: int) -> list[float]:
    if not math.isfinite(lo) or not math.isfinite(hi) or hi <= lo:
        return [lo]
    return [lo + (hi - lo) * k / count for k in range(count + 1)]


def _sentence(text: str) -> str:
    """Capitalise a fragment so it can open a sentence."""
    text = str(text)
    return text[:1].upper() + text[1:] if text else text


def _qty(value: float) -> str:
    v = float(value)
    return f"{v:,.0f}" if abs(v - round(v)) < 1e-9 else f"{v:,.4f}".rstrip("0")


def _price(value: Any, decimals: int) -> str:
    if value is None:
        return "-"
    v = float(value)
    return "-" if v != v else f"{v:,.{decimals}f}"


def _sign_colour(value: Any) -> str:
    try:
        v = float(value)
    except (TypeError, ValueError):
        return PALETTE.text
    if v != v:
        return PALETTE.text_muted
    return PALETTE.long if v > 0 else PALETTE.short if v < 0 else PALETTE.text_dim


def _describe_sizing(risk: Any) -> str:
    mode = risk.sizing_mode
    if mode is SizingMode.FIXED_UNITS:
        text = f"Every position was {risk.fixed_units:g} units."
    elif mode is SizingMode.FIXED_CASH:
        text = (f"Every position was sized to about {risk.fixed_cash:,.0f} of notional "
                f"at the entry price.")
    elif mode is SizingMode.PERCENT_EQUITY:
        text = (f"Every position used {risk.percent_equity:g}% of account equity as "
                f"notional, so size grew with the account and shrank after losses.")
    elif mode is SizingMode.RISK_PERCENT:
        text = (f"Size was set so that the distance from entry to the initial stop "
                f"was worth {risk.risk_percent:g}% of equity. Without a stop there is "
                f"no risk to size against and no position was taken.")
    else:
        text = (f"Size targeted {risk.volatility_target_percent:g}% of equity of "
                f"per-bar volatility, using a {risk.volatility_atr_period}-period ATR "
                f"as the volatility estimate.")
    if risk.use_margin:
        margin = (f"{risk.margin_per_unit:,.2f} per unit" if risk.margin_per_unit > 0
                  else f"{risk.margin_percent:g}% of notional")
        text += (f" Positions were margined at {margin}; a position that could not be "
                 f"margined was not opened.")
    else:
        text += " Positions had to be paid for in full from available cash."
    if risk.max_position_units > 0:
        text += f" Size was capped at {risk.max_position_units:g} units."
    text += (f" At most {risk.max_concurrent_positions} position(s) could be open at "
             f"once. Sizing changes the scale of a result; it does not create an edge.")
    return text


def _weekday_names(days: Iterable[int]) -> str:
    names = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
             "Saturday", "Sunday")
    picked = [names[d] for d in sorted(set(int(d) for d in days)) if 0 <= d < 7]
    if not picked:
        return "no weekdays"
    if len(picked) == 1:
        return picked[0]
    return ", ".join(picked[:-1]) + " and " + picked[-1]


# ==========================================================================
# HTML plumbing
# ==========================================================================

def _e(text: Any) -> str:
    """Escape anything on its way into the document, including attributes."""
    return _html.escape(str(text), quote=True)


def _title_attr(text: str) -> str:
    return f' title="{_e(text)}"' if text else ""


def _badge(ctx: ReportContext, key: str) -> str:
    state = ctx.reliability.get(key, "ok")
    if state == "low_sample":
        return ' <span class="badge low">LOW n</span>'
    if state == "unavailable":
        return ' <span class="badge na">N/A</span>'
    return ""


def _legend_item(colour: str, label: str) -> str:
    return (f'<span class="legend-item"><span class="swatch" '
            f'style="background:{colour}"></span>{_e(label)}</span>')


def _rgba(hex_colour: str, alpha: float) -> str:
    """``#rrggbb`` plus an alpha, as an ``rgba()`` string for SVG fills."""
    text = hex_colour.lstrip("#")
    if len(text) == 3:
        text = "".join(c * 2 for c in text)
    try:
        r, g, b = (int(text[i:i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        r = g = b = 128
    return f"rgba({r},{g},{b},{max(0.0, min(1.0, alpha)):.3f})"


def _css() -> str:
    """The whole stylesheet, built from the application palette.

    Print rules matter as much as screen rules: a report is often read as a PDF
    that someone made with the browser's own print dialogue, so the page is A4,
    backgrounds are forced to print, table headers repeat across pages and no
    card is allowed to break in half.
    """
    p = PALETTE
    ui = UI_FONT_STACK
    mono = MONO_FONT_STACK
    return f"""
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; }}
body {{
  background: {p.app_bg}; color: {p.text};
  font-family: {ui}; font-size: 13px; line-height: 1.45;
  -webkit-print-color-adjust: exact; print-color-adjust: exact;
}}
.page {{ max-width: 1200px; margin: 0 auto; padding: 26px 22px 60px; }}
h2 {{ font-size: 15px; margin: 0 0 10px; color: {p.text}; font-weight: 600; }}
h3 {{ font-size: 12px; margin: 0 0 6px; color: {p.text_dim}; font-weight: 600;
     text-transform: uppercase; letter-spacing: .6px; }}
h3.sub {{ margin-top: 18px; }}
p {{ margin: 0 0 10px; }}
.lede {{ color: {p.text_dim}; font-size: 12px; max-width: 96ch; }}
.note {{ color: {p.warning}; font-size: 12px; }}
.empty {{ color: {p.text_muted}; font-style: italic; }}
.dim {{ color: {p.text_muted}; }}
.strong {{ font-weight: 600; }}
.mono, .num {{ font-family: {mono}; font-variant-numeric: tabular-nums; }}
.num {{ text-align: right; }}

.head {{ border-bottom: 1px solid {p.border_strong}; padding-bottom: 16px;
        margin-bottom: 18px; }}
.head-title {{ font-size: 24px; font-weight: 600; letter-spacing: -.2px; }}
.head-sub {{ color: {p.text_dim}; font-size: 13px; margin-top: 2px; }}
.meta {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
        gap: 2px 22px; margin-top: 14px; }}
.meta-item {{ display: flex; gap: 10px; font-size: 12px; border-bottom: 1px dotted
             {p.border}; padding: 3px 0; }}
.meta-label {{ color: {p.text_muted}; min-width: 116px; }}
.meta-value {{ color: {p.text}; font-family: {mono}; word-break: break-word; }}

.kpis {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px;
        margin-bottom: 16px; }}
.kpi {{ background: {p.panel_alt}; border: 1px solid {p.border}; border-radius: 6px;
       padding: 10px 12px; }}
.kpi-label {{ font-size: 10px; text-transform: uppercase; letter-spacing: .7px;
             color: {p.text_muted}; }}
.kpi-value {{ font-family: {mono}; font-size: 20px; font-weight: 600; margin-top: 3px; }}

.card {{ background: {p.panel_bg}; border: 1px solid {p.border}; border-radius: 8px;
        padding: 16px 18px; margin-bottom: 16px; break-inside: avoid; }}
.card.warn {{ border-color: {p.warning}; }}
.warn-list {{ margin: 0; padding-left: 18px; color: {p.warning}; font-size: 12px; }}
.warn-list li {{ margin-bottom: 4px; }}

.chart {{ width: 100%; height: auto; display: block; background: {p.panel_alt};
         border: 1px solid {p.border}; border-radius: 6px; }}
.heat {{ width: 100%; height: auto; min-width: 760px; display: block; }}
svg text.axis {{ fill: {p.axis_text}; font-family: {mono}; font-size: 11px; }}
svg text.axis.strong {{ fill: {p.text_dim}; }}
svg text.cellv {{ fill: {p.text}; font-family: {mono}; font-size: 11px; }}
.legend {{ display: flex; gap: 16px; margin-top: 8px; font-size: 11px;
          color: {p.text_dim}; }}
.legend-item {{ display: inline-flex; align-items: center; gap: 6px; }}
.swatch {{ width: 14px; height: 3px; border-radius: 2px; display: inline-block; }}

.metric-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(310px, 1fr));
               gap: 14px 26px; }}
.metric-group {{ break-inside: avoid; }}
table.metrics {{ width: 100%; border-collapse: collapse; }}
table.metrics th {{ text-align: left; font-weight: 400; color: {p.text_dim};
                   font-size: 12px; padding: 3px 0; }}
table.metrics td {{ font-family: {mono}; font-size: 12px; padding: 3px 0;
                   white-space: nowrap; }}
table.metrics tr {{ border-bottom: 1px dotted {p.border}; }}

.scroll {{ overflow-x: auto; }}
table.grid {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
table.grid th {{ background: {p.elevated}; color: {p.text_dim}; text-align: left;
                font-weight: 600; padding: 5px 8px; white-space: nowrap;
                border-bottom: 1px solid {p.border_strong}; position: sticky; top: 0; }}
table.grid td {{ padding: 4px 8px; border-bottom: 1px solid {p.grid};
                white-space: nowrap; }}
table.grid tbody tr:nth-child(even) {{ background: {p.panel_alt}; }}
table.grid tr.total td {{ border-top: 1px solid {p.border_strong}; font-weight: 600; }}
table.trades td {{ font-family: {mono}; font-size: 11px; }}
table.grid th.num, table.grid td.num {{ text-align: right; }}

.badge {{ font-size: 9px; letter-spacing: .5px; border-radius: 3px; padding: 0 3px;
         border: 1px solid; vertical-align: middle; font-family: {ui}; }}
.badge.low {{ color: {p.warning}; border-color: {p.warning}; }}
.badge.na {{ color: {p.text_muted}; border-color: {p.border_strong}; }}

.assume-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(330px, 1fr));
               gap: 14px 26px; }}
.assume {{ break-inside: avoid; }}
.assume p {{ font-size: 12px; color: {p.text_dim}; }}
.limits {{ margin-top: 14px; border-top: 1px solid {p.border}; padding-top: 12px; }}
.limits p {{ font-size: 12px; color: {p.text_dim}; max-width: 100ch; }}

@page {{ size: A4 portrait; margin: 12mm; }}
@media print {{
  .page {{ max-width: none; padding: 0; }}
  body {{ font-size: 10px; }}
  .card {{ page-break-inside: avoid; border-radius: 0; }}
  .kpis {{ grid-template-columns: repeat(4, 1fr); }}
  .kpi-value {{ font-size: 15px; }}
  table.grid {{ font-size: 7.5px; }}
  table.trades td {{ font-size: 7px; }}
  table.grid th {{ position: static; }}
  thead {{ display: table-header-group; }}
  tr {{ page-break-inside: avoid; }}
  .scroll {{ overflow: visible; }}
  .heat {{ min-width: 0; }}
}}
"""


__all__ = ["export_html_report", "build_html_report", "ReportContext",
           "METRIC_GROUPS", "MAX_TRADE_ROWS", "decimate_indices"]
