"""Emit the shipped Pine from the same parameter object the research layer simulates.

There is no Pine compiler in this container, so the script is generated rather than hand-edited and
checked two ways: `pine_lint` for the indentation rule that has broken a generated script before,
and a fingerprint block written into the header recording exactly which measurement each preset
came from.

Three Pine definitional traps, all recorded in `CLAUDE.md` as having shipped broken once:

  * bare `hour` / `minute` are EXCHANGE time -- Chicago for CME, and something else again for a
    CFD feed.  Every session test here goes through `time(timeframe.period, session, tz)` with the
    timezone named explicitly, so a New York window stays a New York window;
  * `ta.atr` is Wilder's RMA of true range.  The research engine's `_rma` is the same recursion
    with the same SMA seed, so the two agree bar for bar -- but the repo's *other* studies use
    `ta.ema(ta.tr(true), n)`, which is a different number.  This script uses `ta.atr`;
  * entries are gated on `barstate.isconfirmed`, without which tick evaluation fires several times
    as many signals, most of them on bars that never satisfied the rule.

The one modelled behaviour Pine cannot reproduce exactly is the session-boundary flatten.  The
engine closes a position at the bar's close when the next bar is not in the same session, because
a market order issued at 11:00 on a half day would otherwise rest until the next session's open.
Pine's `strategy.close_all()` always fills at the next bar's open, whatever it is, so the script
also closes on `session.islastbar`.  The residual is measured in the study rather than assumed
away.
"""
from __future__ import annotations

import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from turtle_sim import P

HEADER = '''//@version=5
// {title}
//
// {subtitle}
//
// Generated by research/turtle_pine.py from the measured parameters in
// docs/ib/STUDY_TURTLE_SCALP.md.  Do not hand-edit the preset constants: change the study, re-run
// the emitter.  Every preset below is the winner of a search run on the RESEARCH block only and
// read once on the locked block; the study records both numbers side by side.
//
{fingerprint}
strategy("{title}", overlay = true, pyramiding = {pyramiding},
         default_qty_type = strategy.fixed, default_qty_value = 1,
         initial_capital = 100000, calc_on_every_tick = false,
         process_orders_on_close = false)
'''


def _fmt(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return f"{v:g}"
    return str(v)


def _switch(name: str, presets: dict, field: str, custom: str, kind: str) -> str:
    """A Pine `switch` mapping the preset name to one resolved constant.

    `kind` matters: Pine's `switch` arms must all be the same type, and a bool coerced through
    `float()` emits `1` where the script needs `true`.  A silent type change like that is exactly
    what `verify()` re-reads the generated text to catch.
    """
    lines = [f"{name} = switch presetName"]
    for label, p in presets.items():
        v = getattr(p, field) if isinstance(p, P) else p[field]
        if kind == "bool":
            v = bool(v)
        elif kind == "float":
            v = float(v)
        elif kind == "int":
            v = int(v)
        lines.append(f'    "{label}" => {_fmt(v)}')
    lines.append(f"    => {custom}")
    return "\n".join(lines)


def emit(presets: dict[str, P], sessions: dict[str, tuple[str, str]], design_tf: dict[str, str],
         title: str, subtitle: str, fingerprint: str, pyramiding: int = 4) -> str:
    """Build the full script.  `presets` maps a UI label to the parameters measured for it."""
    labels = list(presets)
    opts = ",\n     ".join(f'"{k}"' for k in labels + ["Custom"])

    def sw(name, field, custom, kind="float"):
        return _switch(name, presets, field, custom, kind)

    sess_sw = ["entrySessDef = switch presetName"]
    for label in labels:
        sess_sw.append(f'    "{label}" => "{sessions[label][0]}"')
    sess_sw.append('    => "0700-1100"')
    tf_sw = ["designTF = switch presetName"]
    for label in labels:
        tf_sw.append(f'    "{label}" => "{design_tf[label]}"')
    tf_sw.append("    => timeframe.period")

    body = f'''
// ----------------------------------------------------------------- preset
presetName = input.string("{labels[0]}", "Preset", options = [
     {opts}],
     tooltip = "Each preset is the configuration selected on that instrument's RESEARCH block and "
             + "read once on its locked block.  Presets also fix the timeframe they were measured "
             + "on -- the HUD turns red on any other.")

// ----------------------------------------------------------------- session (free, never locked)
// The window is the reason this strategy exists, so it stays editable; a changed window is
// reported in the HUD so it can never be invisible in a screenshot.
sessTZ    = input.string("America/New_York", "Session timezone", group = "Session",
     options = ["America/New_York", "America/Chicago", "Europe/London", "UTC"])
entrySess = input.string("", "Entry window (blank = preset)", group = "Session",
     tooltip = "Entries are allowed only inside this window.  Blank uses the preset's own measured "
             + "window, which is never wider than 07:00-11:00 New York.")
flatAt    = input.string("1100-1105", "Flatten window", group = "Session",
     tooltip = "The position is closed on the first bar inside this window.  A scalp that is still "
             + "open when the session ends is not a scalp.")

// ----------------------------------------------------------------- custom (used only by Custom)
cEntry1   = input.int(20,  "Custom entry 1 (bars)",  minval = 2, group = "Custom only")
cEntry2   = input.int(55,  "Custom entry 2 (bars)",  minval = 2, group = "Custom only")
cExit1    = input.int(10,  "Custom exit 1 (bars)",   minval = 2, group = "Custom only")
cExit2    = input.int(20,  "Custom exit 2 (bars)",   minval = 2, group = "Custom only")
cAtrLen   = input.int(20,  "Custom ATR length",      minval = 2, group = "Custom only")
cAtrMult  = input.float(2.0, "Custom ATR stop multiple", minval = 0.1, group = "Custom only")
cPyrStep  = input.float(0.5, "Custom pyramid step (N)",  minval = 0.0, group = "Custom only")
cMaxUnits = input.int(4,   "Custom max units", minval = 1, maxval = {pyramiding}, group = "Custom only")
cTpR      = input.float(0, "Custom take profit (R, 0 = off)", minval = 0, group = "Custom only")
cMaxHold  = input.int(0,   "Custom max hold (bars, 0 = off)", minval = 0, group = "Custom only")
cAdxMax   = input.float(0, "Custom ADX ceiling (0 = off)", minval = 0, group = "Custom only")
cExtMax   = input.float(0, "Custom max distance above EMA100 in ATR (0 = off)", minval = 0,
     group = "Custom only")
cSkipWin  = input.bool(true,  "Custom: skip System 1 after a win", group = "Custom only")
cChanExit = input.bool(true,  "Custom: trailing channel exit",     group = "Custom only")
cArmed    = input.bool(false, "Custom: stop live on the entry bar", group = "Custom only")
cOneShot  = input.bool(false, "Custom: at most one trade per session", group = "Custom only")
cChanShift = input.int(1, "Custom: trailing channel lag (bars)", minval = 0, maxval = 3,
     group = "Custom only")

// ----------------------------------------------------------------- resolved constants
isCustom = presetName == "Custom"
{sw("entry1P", "entry1", "cEntry1", "int")}
{sw("entry2P", "entry2", "cEntry2", "int")}
{sw("exit1P", "exit1", "cExit1", "int")}
{sw("exit2P", "exit2", "cExit2", "int")}
{sw("atrLenP", "atr_len", "cAtrLen", "int")}
{sw("atrMultP", "atr_mult", "cAtrMult")}
{sw("pyrStepP", "pyr_step", "cPyrStep")}
{sw("maxUnitsP", "max_units", "cMaxUnits", "int")}
{sw("tpRP", "tp_r", "cTpR")}
{sw("maxHoldP", "max_hold", "cMaxHold", "int")}
{sw("adxMaxP", "adx_max", "cAdxMax")}
{sw("extMaxP", "ext_max", "cExtMax")}
{sw("skipWinP", "skip_win", "cSkipWin", "bool")}
{sw("chanExitP", "use_chan_exit", "cChanExit", "bool")}
{sw("armedStopP", "armed_stop", "cArmed", "bool")}
{sw("oneShotP", "one_shot", "cOneShot", "bool")}
{sw("chanShiftP", "chan_shift", "cChanShift", "int")}
{chr(10).join(sess_sw)}
{chr(10).join(tf_sw)}

entry1   = entry1P
entry2   = entry2P
exit1    = exit1P
exit2    = exit2P
atrLen   = atrLenP
atrMult  = atrMultP
pyrStep  = pyrStepP
maxUnits = maxUnitsP
tpR      = tpRP
maxHold  = maxHoldP
adxMax   = adxMaxP
extMax   = extMaxP
skipWin  = skipWinP
chanExit = chanExitP
armedStp = armedStopP
oneShot  = oneShotP
chanLag  = chanShiftP
sessUsed = entrySess == "" ? entrySessDef : entrySess

onDesignTF = isCustom or timeframe.period == designTF

// ----------------------------------------------------------------- series
// ta.atr is Wilder's RMA of true range.  The research engine uses the same recursion with the same
// SMA seed, so the two agree bar for bar; ta.ema(ta.tr(true), n) is a DIFFERENT number and is what
// other scripts in this repository use.  Do not swap one for the other here.
atrN    = ta.atr(atrLen)
chanHi1 = ta.highest(high, entry1)
chanHi2 = ta.highest(high, entry2)
chanLo1 = ta.lowest(low,  exit1)
chanLo2 = ta.lowest(low,  exit2)
ema100  = ta.ema(close, 100)
[diPlus, diMinus, adxVal] = ta.dmi(14, 14)
distEma = atrN > 0 ? (close - ema100) / atrN : 0.0

// ----------------------------------------------------------------- gates
inEntry = not na(time(timeframe.period, sessUsed, sessTZ))
inFlat  = not na(time(timeframe.period, flatAt,   sessTZ))
adxOk   = adxMax <= 0 or adxVal < adxMax
extOk   = extMax <= 0 or distEma < extMax
gateOk  = adxOk and extOk and inEntry and onDesignTF

// ----------------------------------------------------------------- state
// The stop, the ladder and the take-profit are anchored to the ACTUAL FILL, not to the signal
// bar's close: with process_orders_on_close = false the fill happens at the NEXT bar's open, so
// anchoring is done one bar later, from the price the broker emulator actually reports.
var float stopLvl   = na
var float nextAdd   = na
var float tpLvl     = na
var float firstFill = na
var float pendAtr   = na
var float initRisk  = na
var int   unitsOn   = 0
var int   sysOn     = 0
var int   lastCount = 0
var int   entryBar  = na
var int   sessTrade = na
var bool  lastWin   = false

if strategy.position_size == 0 and lastCount > 0
    lastWin   := close > firstFill
    unitsOn   := 0
    sysOn     := 0
    stopLvl   := na
    nextAdd   := na
    tpLvl     := na
    lastCount := 0

if strategy.opentrades > lastCount
    fillPx = strategy.opentrades.entry_price(strategy.opentrades - 1)
    anchorAtr = na(pendAtr) ? atrN : pendAtr
    if lastCount == 0
        firstFill := fillPx
        entryBar  := bar_index
        initRisk  := atrMult * anchorAtr
        tpLvl     := tpR > 0 ? fillPx + tpR * initRisk : na
        sessTrade := dayofmonth(time, sessTZ) * 100 + month(time, sessTZ)
    stopLvl   := fillPx - atrMult * anchorAtr
    nextAdd   := fillPx + pyrStep * anchorAtr
    unitsOn   := strategy.opentrades
    lastCount := strategy.opentrades

flat = strategy.position_size == 0
// Bare `dayofmonth` / `month` are EXCHANGE time.  For a CFD feed that is neither New York
// nor anything the session strings use, so a one-trade-per-session rule keyed on them would
// roll over at the wrong hour.  Both are read in the session timezone instead.
sameSess = not na(sessTrade)
     and sessTrade == dayofmonth(time, sessTZ) * 100 + month(time, sessTZ)

// ----------------------------------------------------------------- entries
sig2 = high > chanHi2[1]
sig1 = high > chanHi1[1]

// ----------------------------------------------------------------- exit level
// One stop at the HIGHER of the ATR stop and the trailing channel low: a falling price reaches
// that level first.  The channel is read as of the PREVIOUS bar when chanLag is 1, which is what
// the original script's `chanLo1[1]` does; chanLag 0 uses this bar's, which trails looser because
// including the current bar can only push the low down.  When a bar contains both this stop and
// the take-profit, TradingView's broker emulator assumes the least favourable intrabar path and
// fills the stop -- the same pessimism the research engine applies, so the two agree there.
chanRaw1    = chanLag == 1 ? chanLo1[1] : chanLo1
chanRaw2    = chanLag == 1 ? chanLo2[1] : chanLo2
chanExitLvl = sysOn == 1 ? chanRaw1 : chanRaw2
stopOnly    = na(stopLvl) ? chanExitLvl : stopLvl
exitLevel   = not chanExit ? stopOnly
     : (na(chanExitLvl) ? stopOnly : (na(stopLvl) ? chanExitLvl : math.max(stopLvl, chanExitLvl)))

heldTooLong = maxHold > 0 and not na(entryBar) and (bar_index - entryBar) >= maxHold

// ----------------------------------------------------------------- entries
// Every entry is bracketed on the bar it is ORDERED, not on the bar after it fills.  That is what
// makes the two behaviours below reproducible in Pine at all:
//   * `armedStp` -- the stop is live on the entry bar itself, anchored to the signal bar's close
//     because the fill price does not exist yet.  With armedStp off no bracket is placed with the
//     order, so the first bar of a position is unprotected, which is what the original script does
//     (it reads `strategy.opentrades.entry_price`, which needs the fill to have happened).
//   * a pyramid add is bracketed at the level every other unit is already carrying, so the whole
//     position exits together on the add's own fill bar rather than leaving the newest unit naked.
if barstate.isconfirmed and flat and gateOk and atrN > 0 and not (oneShot and sameSess)
    armLvl = close - atrMult * atrN
    if sig2
        strategy.entry("S2", strategy.long, qty = 1)
        sysOn   := 2
        pendAtr := atrN
        if armedStp
            strategy.exit("xS2", from_entry = "S2", stop = armLvl)
    else if sig1
        if skipWin and lastWin
            lastWin := false
        else
            strategy.entry("S1", strategy.long, qty = 1)
            sysOn   := 1
            pendAtr := atrN
            if armedStp
                strategy.exit("xS1", from_entry = "S1", stop = armLvl)

// ----------------------------------------------------------------- pyramid adds
if barstate.isconfirmed and not flat and unitsOn > 0 and unitsOn < maxUnits and pyrStep > 0
     and not inFlat and not heldTooLong
    if high >= nextAdd
        addId = "add" + str.tostring(unitsOn + 1)
        strategy.entry(addId, strategy.long, qty = 1)
        pendAtr := atrN
        if not na(exitLevel)
            strategy.exit("x" + addId, from_entry = addId, stop = exitLevel,
                 limit = na(tpLvl) ? na : tpLvl)

// ----------------------------------------------------------------- exit
// The bracket for every open unit is refreshed each bar with the current level.  Refreshing per
// entry rather than issuing one position-wide exit keeps the ids stable, so an update replaces an
// order instead of stacking a second one on the same unit.
if not flat
    if inFlat or heldTooLong or session.islastbar
        strategy.close_all(comment = "flat")
    else if not na(exitLevel)
        for k = 0 to strategy.opentrades - 1
            eid = strategy.opentrades.entry_id(k)
            strategy.exit("x" + eid, from_entry = eid, stop = exitLevel,
                 limit = na(tpLvl) ? na : tpLvl)

// ----------------------------------------------------------------- plots
plot(chanHi1, "Entry 1", color = color.new(color.aqua, 40))
plot(chanHi2, "Entry 2", color = color.new(color.blue, 40))
plot(chanExit ? chanLo1 : na, "Exit 1", color = color.new(color.red, 60))
plot(chanExit ? chanLo2 : na, "Exit 2", color = color.new(color.purple, 60))
plot(flat ? na : exitLevel, "Active stop", color = color.fuchsia, style = plot.style_linebr)
plot(flat or na(tpLvl) ? na : tpLvl, "Take profit", color = color.lime,
     style = plot.style_linebr)
bgcolor(inEntry ? color.new(color.teal, 92) : na, title = "Entry window")

// A changed session, or the wrong timeframe, must never be invisible in a screenshot.
var table hud = table.new(position.top_right, 1, 4, border_width = 1)
if barstate.islast
    table.cell(hud, 0, 0, presetName, text_color = color.white,
         bgcolor = onDesignTF ? color.new(color.teal, 20) : color.new(color.red, 10))
    table.cell(hud, 0, 1, onDesignTF ? "timeframe OK" : "WRONG TIMEFRAME - needs " + designTF,
         text_color = color.white, bgcolor = onDesignTF ? color.new(color.teal, 40) : color.red)
    table.cell(hud, 0, 2, "entries " + sessUsed + "  flat " + flatAt + "  " + sessTZ,
         text_color = color.white,
         bgcolor = entrySess == "" ? color.new(color.gray, 40) : color.new(color.orange, 20))
    table.cell(hud, 0, 3, "N=" + str.tostring(atrLen) + " x" + str.tostring(atrMult)
         + "  ch " + str.tostring(entry1) + "/" + str.tostring(entry2)
         + "  ex " + str.tostring(exit1) + "/" + str.tostring(exit2)
         + (tpR > 0 ? "  TP " + str.tostring(tpR) + "R" : "  no TP"),
         text_color = color.white, bgcolor = color.new(color.gray, 40))
'''
    return HEADER.format(title=title, subtitle=subtitle, fingerprint=fingerprint,
                         pyramiding=pyramiding) + body


def write(path: str, text: str, verbose: bool = True) -> list:
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import pine_lint
    problems = pine_lint.check(text, os.path.basename(path), verbose=verbose)
    with open(path, "w") as fh:
        fh.write(text)
    return problems


__all__ = ["emit", "write"]


# ================================================================= read the emitted script back

_SWITCH = None


def parse_presets(text: str) -> dict[str, dict]:
    """Re-read the emitted script's `switch` blocks into {preset: {field: value}}.

    Emitting a script from a parameter object and then trusting it is one step short of the job:
    a template typo puts a number in the chart that no measurement produced.  This parses the
    generated text back with no knowledge of what was written, so `verify` compares two
    independent readings of the same file.
    """
    import re
    fields = {}
    cur = None
    for raw in text.split("\n"):
        m = re.match(r"^(\w+) = switch presetName\s*$", raw)
        if m:
            cur = m.group(1)
            fields[cur] = {}
            continue
        if cur is None:
            continue
        m = re.match(r'^    "(.+)" => (.+?)\s*$', raw)
        if m:
            fields[cur][m.group(1)] = m.group(2)
            continue
        if raw.startswith("    => "):
            cur = None
            continue
        if raw.strip() and not raw.startswith("    "):
            cur = None
    out: dict[str, dict] = {}
    for var, arms in fields.items():
        for label, val in arms.items():
            out.setdefault(label, {})[var] = val
    return out


FIELD_VAR = {
    "entry1": "entry1P", "entry2": "entry2P", "exit1": "exit1P", "exit2": "exit2P",
    "atr_len": "atrLenP", "atr_mult": "atrMultP", "pyr_step": "pyrStepP",
    "max_units": "maxUnitsP", "tp_r": "tpRP", "max_hold": "maxHoldP",
    "adx_max": "adxMaxP", "ext_max": "extMaxP", "skip_win": "skipWinP",
    "use_chan_exit": "chanExitP", "one_shot": "oneShotP", "armed_stop": "armedStopP",
    "chan_shift": "chanShiftP",
}


def verify(text: str, presets: dict[str, P], sessions: dict[str, tuple[str, str]]) -> list[str]:
    """Every preset constant in the emitted text must equal the measured parameter."""
    got = parse_presets(text)
    problems = []
    for label, p in presets.items():
        if label not in got:
            problems.append(f"{label}: missing from the emitted script")
            continue
        for field, var in FIELD_VAR.items():
            want = getattr(p, field)
            have = got[label].get(var)
            if have is None:
                problems.append(f"{label}.{field}: no `{var}` arm emitted")
                continue
            if isinstance(want, bool):
                ok = have == ("true" if want else "false")
            else:
                try:
                    ok = abs(float(have) - float(want)) < 1e-9
                except ValueError:
                    ok = False
            if not ok:
                problems.append(f"{label}.{field}: emitted {have!r}, measured {want!r}")
        sess = got[label].get("entrySessDef", "").strip('"')
        if sess != sessions[label][0]:
            problems.append(f"{label}.session: emitted {sess!r}, measured {sessions[label][0]!r}")
        # The window a preset was measured in must match the string the chart will evaluate.
        want_sess = f"{p.sess_start // 60:02d}{p.sess_start % 60:02d}-" \
                    f"{p.sess_end // 60:02d}{p.sess_end % 60:02d}"
        if sess != want_sess:
            problems.append(f"{label}.session: emitted {sess!r} but parameters say {want_sess!r}")
    return problems
