"""Emit the shipped Pine from the same parameter object the research layer simulates.

There is no Pine compiler in this container, so the script is generated rather than hand-edited and
checked two ways: `pine_lint` for the indentation rule that has broken a generated script before,
and a fingerprint block written into the header recording exactly which measurement each preset
came from.

Three Pine definitional traps, all recorded in `CLAUDE.md` as having shipped broken once:

  * bare `hour` / `minute` are EXCHANGE time -- Chicago for CME, and something else again for a
    CFD feed.  Every session test here goes through `time(timeframe.period, session, tz)` with the
    timezone named explicitly, so a New York window stays a New York window;
  * `ta.atr` is Wilder's RMA of true range.  The research engine's `_rma` is the same recursion
    with the same SMA seed, so the two agree bar for bar -- but the repo's *other* studies use
    `ta.ema(ta.tr(true), n)`, which is a different number.  This script uses `ta.atr`;
  * entries are gated on `barstate.isconfirmed`, without which tick evaluation fires several times
    as many signals, most of them on bars that never satisfied the rule.

The one modelled behaviour Pine cannot reproduce exactly is the session-boundary flatten.  The
engine closes a position at the bar's close when the next bar is not in the same session, because
a market order issued at 11:00 on a half day would otherwise rest until the next session's open.
Pine's `strategy.close_all()` always fills at the next bar's open, whatever it is, so the script
also closes on `session.islastbar`.  The residual is measured in the study rather than assumed
away.
"""
from __future__ import annotations

import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from turtle_sim import P

HEADER = '''//@version=5
// {title}
//
// {subtitle}
//
// Generated by research/turtle_pine.py from the measured parameters in
// docs/ib/STUDY_TURTLE_SCALP.md.  Do not hand-edit the preset constants: change the study, re-run
// the emitter.  Every preset below is the winner of a search run on the RESEARCH block only and
// read once on the locked block; the study records both numbers side by side.
//
{fingerprint}
strategy("{title}", overlay = true, pyramiding = {pyramiding},
         default_qty_type = strategy.fixed, default_qty_value = 1,
         initial_capital = 100000, calc_on_every_tick = false,
         process_orders_on_close = false)
'''


def _fmt(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, float):
        return f"{v:g}"
    return str(v)


def _switch(name: str, presets: dict, field: str, custom: str, kind: str) -> str:
    """A Pine `switch` mapping the preset name to one resolved constant."""
    lines = [f"{name} = switch presetName"]
    for label, p in presets.items():
        v = getattr(p, field) if isinstance(p, P) else p[field]
        if kind == "float":
            v = float(v)
        elif kind == "int":
            v = int(v)
        lines.append(f'    "{label}" => {_fmt(v)}')
    lines.append(f"    => {custom}")
    return "\n".join(lines)


def emit(presets: dict[str, P], sessions: dict[str, tuple[str, str]], design_tf: dict[str, str],
         title: str, subtitle: str, fingerprint: str, pyramiding: int = 4) -> str:
    """Build the full script.  `presets` maps a UI label to the parameters measured for it."""
    labels = list(presets)
    opts = ",\n     ".join(f'"{k}"' for k in labels + ["Custom"])

    def sw(name, field, custom, kind="float"):
        return _switch(name, presets, field, custom, kind)

    sess_sw = ["entrySessDef = switch presetName"]
    for label in labels:
        sess_sw.append(f'    "{label}" => "{sessions[label][0]}"')
    sess_sw.append('    => "0700-1100"')
    tf_sw = ["designTF = switch presetName"]
    for label in labels:
        tf_sw.append(f'    "{label}" => "{design_tf[label]}"')
    tf_sw.append("    => timeframe.period")

    body = f'''
// ----------------------------------------------------------------- preset
presetName = input.string("{labels[0]}", "Preset", options = [
     {opts}],
     tooltip = "Each preset is the configuration selected on that instrument's RESEARCH block and "
             + "read once on its locked block.  Presets also fix the timeframe they were measured "
             + "on -- the HUD turns red on any other.")

// ----------------------------------------------------------------- session (free, never locked)
// The window is the reason this strategy exists, so it stays editable; a changed window is
// reported in the HUD so it can never be invisible in a screenshot.
sessTZ    = input.string("America/New_York", "Session timezone", group = "Session",
     options = ["America/New_York", "America/Chicago", "Europe/London", "UTC"])
entrySess = input.string("", "Entry window (blank = preset)", group = "Session",
     tooltip = "Entries are allowed only inside this window.  Blank uses the preset's own measured "
             + "window, which is never wider than 07:00-11:00 New York.")
flatAt    = input.string("1100-1105", "Flatten window", group = "Session",
     tooltip = "The position is closed on the first bar inside this window.  A scalp that is still "
             + "open when the session ends is not a scalp.")

// ----------------------------------------------------------------- custom (used only by Custom)
cEntry1   = input.int(20,  "Custom entry 1 (bars)",  minval = 2, group = "Custom only")
cEntry2   = input.int(55,  "Custom entry 2 (bars)",  minval = 2, group = "Custom only")
cExit1    = input.int(10,  "Custom exit 1 (bars)",   minval = 2, group = "Custom only")
cExit2    = input.int(20,  "Custom exit 2 (bars)",   minval = 2, group = "Custom only")
cAtrLen   = input.int(20,  "Custom ATR length",      minval = 2, group = "Custom only")
cAtrMult  = input.float(2.0, "Custom ATR stop multiple", minval = 0.1, group = "Custom only")
cPyrStep  = input.float(0.5, "Custom pyramid step (N)",  minval = 0.0, group = "Custom only")
cMaxUnits = input.int(4,   "Custom max units", minval = 1, maxval = {pyramiding}, group = "Custom only")
cTpR      = input.float(0, "Custom take profit (R, 0 = off)", minval = 0, group = "Custom only")
cMaxHold  = input.int(0,   "Custom max hold (bars, 0 = off)", minval = 0, group = "Custom only")
cAdxMax   = input.float(0, "Custom ADX ceiling (0 = off)", minval = 0, group = "Custom only")
cExtMax   = input.float(0, "Custom max distance above EMA100 in ATR (0 = off)", minval = 0,
     group = "Custom only")
cSkipWin  = input.bool(true,  "Custom: skip System 1 after a win", group = "Custom only")
cChanExit = input.bool(true,  "Custom: trailing channel exit",     group = "Custom only")
cOneShot  = input.bool(false, "Custom: at most one trade per session", group = "Custom only")

// ----------------------------------------------------------------- resolved constants
isCustom = presetName == "Custom"
{sw("entry1P", "entry1", "cEntry1", "int")}
{sw("entry2P", "entry2", "cEntry2", "int")}
{sw("exit1P", "exit1", "cExit1", "int")}
{sw("exit2P", "exit2", "cExit2", "int")}
{sw("atrLenP", "atr_len", "cAtrLen", "int")}
{sw("atrMultP", "atr_mult", "cAtrMult")}
{sw("pyrStepP", "pyr_step", "cPyrStep")}
{sw("maxUnitsP", "max_units", "cMaxUnits", "int")}
{sw("tpRP", "tp_r", "cTpR")}
{sw("maxHoldP", "max_hold", "cMaxHold", "int")}
{sw("adxMaxP", "adx_max", "cAdxMax")}
{sw("extMaxP", "ext_max", "cExtMax")}
{sw("skipWinP", "skip_win", "cSkipWin")}
{sw("chanExitP", "use_chan_exit", "cChanExit")}
{sw("oneShotP", "one_shot", "cOneShot")}
{chr(10).join(sess_sw)}
{chr(10).join(tf_sw)}

entry1   = entry1P
entry2   = entry2P
exit1    = exit1P
exit2    = exit2P
atrLen   = atrLenP
atrMult  = atrMultP
pyrStep  = pyrStepP
maxUnits = maxUnitsP
tpR      = tpRP
maxHold  = maxHoldP
adxMax   = adxMaxP
extMax   = extMaxP
skipWin  = skipWinP
chanExit = chanExitP
oneShot  = oneShotP
sessUsed = entrySess == "" ? entrySessDef : entrySess

onDesignTF = isCustom or timeframe.period == designTF

// ----------------------------------------------------------------- series
// ta.atr is Wilder's RMA of true range.  The research engine uses the same recursion with the same
// SMA seed, so the two agree bar for bar; ta.ema(ta.tr(true), n) is a DIFFERENT number and is what
// other scripts in this repository use.  Do not swap one for the other here.
atrN    = ta.atr(atrLen)
chanHi1 = ta.highest(high, entry1)
chanHi2 = ta.highest(high, entry2)
chanLo1 = ta.lowest(low,  exit1)
chanLo2 = ta.lowest(low,  exit2)
ema100  = ta.ema(close, 100)
[diPlus, diMinus, adxVal] = ta.dmi(14, 14)
distEma = atrN > 0 ? (close - ema100) / atrN : 0.0

// ----------------------------------------------------------------- gates
inEntry = not na(time(timeframe.period, sessUsed, sessTZ))
inFlat  = not na(time(timeframe.period, flatAt,   sessTZ))
adxOk   = adxMax <= 0 or adxVal < adxMax
extOk   = extMax <= 0 or distEma < extMax
gateOk  = adxOk and extOk and inEntry and onDesignTF

// ----------------------------------------------------------------- state
// The stop, the ladder and the take-profit are anchored to the ACTUAL FILL, not to the signal
// bar's close: with process_orders_on_close = false the fill happens at the NEXT bar's open, so
// anchoring is done one bar later, from the price the broker emulator actually reports.
var float stopLvl   = na
var float nextAdd   = na
var float tpLvl     = na
var float firstFill = na
var float pendAtr   = na
var float initRisk  = na
var int   unitsOn   = 0
var int   sysOn     = 0
var int   lastCount = 0
var int   entryBar  = na
var int   sessTrade = na
var bool  lastWin   = false

if strategy.position_size == 0 and lastCount > 0
    lastWin   := close > firstFill
    unitsOn   := 0
    sysOn     := 0
    stopLvl   := na
    nextAdd   := na
    tpLvl     := na
    lastCount := 0

if strategy.opentrades > lastCount
    fillPx = strategy.opentrades.entry_price(strategy.opentrades - 1)
    anchorAtr = na(pendAtr) ? atrN : pendAtr
    if lastCount == 0
        firstFill := fillPx
        entryBar  := bar_index
        initRisk  := atrMult * anchorAtr
        tpLvl     := tpR > 0 ? fillPx + tpR * initRisk : na
        sessTrade := dayofmonth * 100 + month
    stopLvl   := fillPx - atrMult * anchorAtr
    nextAdd   := fillPx + pyrStep * anchorAtr
    unitsOn   := strategy.opentrades
    lastCount := strategy.opentrades

flat = strategy.position_size == 0
sameSess = not na(sessTrade) and sessTrade == dayofmonth * 100 + month

// ----------------------------------------------------------------- entries
sig2 = high > chanHi2[1]
sig1 = high > chanHi1[1]

if barstate.isconfirmed and flat and gateOk and atrN > 0 and not (oneShot and sameSess)
    if sig2
        strategy.entry("S2", strategy.long, qty = 1)
        sysOn   := 2
        pendAtr := atrN
    else if sig1
        if skipWin and lastWin
            lastWin := false
        else
            strategy.entry("S1", strategy.long, qty = 1)
            sysOn   := 1
            pendAtr := atrN

// ----------------------------------------------------------------- pyramid adds
if barstate.isconfirmed and not flat and unitsOn > 0 and unitsOn < maxUnits and pyrStep > 0
     and not inFlat
    if high >= nextAdd
        strategy.entry("add" + str.tostring(unitsOn + 1), strategy.long, qty = 1)
        pendAtr := atrN

// ----------------------------------------------------------------- exit
// One stop at the HIGHER of the ATR stop and the trailing channel low: a falling price reaches
// that level first.  When a bar contains both this stop and the take-profit, TradingView's broker
// emulator assumes the least favourable intrabar path and fills the stop -- which is the same
// pessimism the research engine applies, so the two agree on the ambiguous bars.
chanExitLvl = sysOn == 1 ? chanLo1[1] : chanLo2[1]
stopOnly    = na(stopLvl) ? chanExitLvl : stopLvl
exitLevel   = not chanExit ? stopOnly
     : (na(chanExitLvl) ? stopOnly : (na(stopLvl) ? chanExitLvl : math.max(stopLvl, chanExitLvl)))

heldTooLong = maxHold > 0 and not na(entryBar) and (bar_index - entryBar) >= maxHold

if not flat
    if inFlat or heldTooLong or session.islastbar
        strategy.close_all(comment = "flat")
    else if not na(exitLevel)
        if na(tpLvl)
            strategy.exit("x", stop = exitLevel)
        else
            strategy.exit("x", stop = exitLevel, limit = tpLvl)

// ----------------------------------------------------------------- plots
plot(chanHi1, "Entry 1", color = color.new(color.aqua, 40))
plot(chanHi2, "Entry 2", color = color.new(color.blue, 40))
plot(chanExit ? chanLo1 : na, "Exit 1", color = color.new(color.red, 60))
plot(chanExit ? chanLo2 : na, "Exit 2", color = color.new(color.purple, 60))
plot(flat ? na : exitLevel, "Active stop", color = color.fuchsia, style = plot.style_linebr)
plot(flat or na(tpLvl) ? na : tpLvl, "Take profit", color = color.lime,
     style = plot.style_linebr)
bgcolor(inEntry ? color.new(color.teal, 92) : na, title = "Entry window")

// A changed session, or the wrong timeframe, must never be invisible in a screenshot.
var table hud = table.new(position.top_right, 1, 4, border_width = 1)
if barstate.islast
    table.cell(hud, 0, 0, presetName, text_color = color.white,
         bgcolor = onDesignTF ? color.new(color.teal, 20) : color.new(color.red, 10))
    table.cell(hud, 0, 1, onDesignTF ? "timeframe OK" : "WRONG TIMEFRAME - needs " + designTF,
         text_color = color.white, bgcolor = onDesignTF ? color.new(color.teal, 40) : color.red)
    table.cell(hud, 0, 2, "entries " + sessUsed + "  flat " + flatAt + "  " + sessTZ,
         text_color = color.white,
         bgcolor = entrySess == "" ? color.new(color.gray, 40) : color.new(color.orange, 20))
    table.cell(hud, 0, 3, "N=" + str.tostring(atrLen) + " x" + str.tostring(atrMult)
         + "  ch " + str.tostring(entry1) + "/" + str.tostring(entry2)
         + "  ex " + str.tostring(exit1) + "/" + str.tostring(exit2)
         + (tpR > 0 ? "  TP " + str.tostring(tpR) + "R" : "  no TP"),
         text_color = color.white, bgcolor = color.new(color.gray, 40))
'''
    return HEADER.format(title=title, subtitle=subtitle, fingerprint=fingerprint,
                         pyramiding=pyramiding) + body


def write(path: str, text: str, verbose: bool = True) -> list:
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import pine_lint
    problems = pine_lint.check(text, os.path.basename(path), verbose=verbose)
    with open(path, "w") as fh:
        fh.write(text)
    return problems


__all__ = ["emit", "write"]
