"""Emit the LIVE-defaults variant of the 09:00-range script FROM the research file.

WHY GENERATED AND NOT HAND-EDITED. Two copies of a 500-line strategy drift, and the drift is
invisible: a tooltip is edited in one, a guard reordered in the other, and six months later the
file someone is trading is not the file that was measured. `research/turtle2/yt_gates.py` records
the pattern -- a frozen kernel is COPIED and then ASSERTED identical, never re-typed.

So this rewrites ONLY the default value of named `input.*` calls and then PROVES it: every line
that is not one of the declared inputs must be byte-identical to the research file, and the count
of changed lines must equal the count of fields asked for. If anything else moved, it raises.

The result is provably the same strategy with different starting values in the dialog -- which is
all a "live preset" should ever be. It is a separate FILE rather than a preset input because a
preset that overwrites a setting silently disarms the switch a reader most wants to try
(STUDY_V60), and because a file cannot be half-applied.
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "pine", "nineam", "NINE_AM_RANGE_BREAKOUT_strategy.pine")
DST = os.path.join(ROOT, "pine", "nineam", "NINE_AM_RANGE_LIVE_30s_strategy.pine")

# `na_live.TV35` -- the configuration the user TRADES (section 28) -- expressed as this script's own
# inputs. The chart guard checks the same fields, so a mismatch shows up in red rather than silently.
LIVE = {
    "rangeStart":  "540",
    "rangeEnd":    "545",
    "firstEntry":  "567",
    "lastEntry":   "600",
    "flatMin":     "660",
    "atrLen":      "14",
    "sideIn":      '"Both"',
    "bufAtr":      "0.0",
    "touchOk":     "true",
    "maMode":      '"Fresh cross"',
    "crossMin":    "3.5",            # 7 BARS on a 30-second chart: the rule the TradingView record ran
    "confBypass":  '"Off"',
    "crossBypass": '"Off"',
    "stopMode":    '"Points"',
    "stopPts":     "100",
    "tgtMode":     '"Points"',
    "tgtPts":      "100",
    "beMode":      '"Points"',
    "bePts":       "43",
    "beOffset":    "3",
    "xMode":       '"Fresh opposite cross"',
    "alertOn":     "true",          # this file exists to be traded from
}


def rewrite(line: str, name: str, value: str) -> str:
    """Replace only the FIRST argument of `input.*(` -- the default -- and nothing else."""
    m = re.match(rf"(\s*{re.escape(name)}\s*=\s*input\.\w+\()", line)
    if not m:
        return line
    head = m.group(1)
    rest = line[len(head):]
    # the default runs to the first top-level comma
    depth = 0
    for i, ch in enumerate(rest):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            return head + value + rest[i:]
    raise SystemExit(f"could not find the default argument for {name}")


def main():
    src = open(SRC).read().split("\n")
    out, found, changed = [], {}, {}
    for ln in src:
        new = ln
        for name, val in LIVE.items():
            if not re.match(rf"\s*{re.escape(name)}\s*=\s*input\.\w+\(", ln):
                continue
            cand = rewrite(ln, name, val)
            found[name] = cand.strip()
            # a field whose research default ALREADY equals the live value is found and
            # unchanged; that is not an error, and conflating the two hides a real miss.
            if cand != ln:
                changed[name] = (ln.strip(), cand.strip())
            new = cand
            break
        out.append(new)

    missing = set(LIVE) - set(found)
    if missing:
        raise SystemExit(f"these inputs were never found in the source: {sorted(missing)}")

    # ---- the proof: nothing but the CHANGED lines moved
    diffs = [i for i, (a, b) in enumerate(zip(src, out)) if a != b]
    if len(diffs) != len(changed):
        raise SystemExit(f"{len(diffs)} lines differ but {len(changed)} fields were rewritten")
    if len(src) != len(out):
        raise SystemExit("line count changed")

    # retitle so the two cannot be confused in the TradingView indicator list
    body = "\n".join(out)
    body = body.replace('strategy("09:00 Range Breakout + EMA Momentum"',
                        'strategy("09:00 Range Breakout -- LIVE 30s preset"', 1)
    header = (
        "// GENERATED BY research/nineam/mk_live_pine.py -- DO NOT EDIT BY HAND.\n"
        "// Identical logic to NINE_AM_RANGE_BREAKOUT_strategy.pine; only the INPUT DEFAULTS\n"
        "// differ, and the generator asserts that exactly the declared fields moved and nothing\n"
        "// else. Re-run it after any change to the research file.\n"
        "//\n"
        "// The defaults are `na_live.TV35`, the configuration the user trades: the fresh cross is\n"
        "// 3.5 MINUTES = 7 bars on a 30-second chart, which is what produced the 109-trade\n"
        "// TradingView record (section 27). The HUD's `traded cfg` row must read MATCHES on a\n"
        "// 30-second chart. Not out of sample -- the settings were chosen on that record.\n")
    open(DST, "w").write(header + body)

    print(f"wrote {os.path.relpath(DST, ROOT)}")
    print(f"  {len(found)} of {len(LIVE)} declared inputs located in the source")
    print(f"  {len(changed)} rewritten, {len(found)-len(changed)} already at the live value")
    print(f"  {len(diffs)} lines differ -- exactly the rewritten ones; the other "
          f"{len(src)-len(diffs)} are byte-identical\n")
    for k in LIVE:
        if k in changed:
            a, b = changed[k]
            fa = a.split("input.")[1].split("(")[1].split(",")[0]
            fb = b.split("input.")[1].split("(")[1].split(",")[0]
            print(f"    {k:12s} {fa:26s} -> {fb}")
        else:
            print(f"    {k:12s} {'(already live value)':26s}")


if __name__ == "__main__":
    main()
