"""Synthetic market data that behaves like the real thing.

Every installation needs something to open on the first run, and the only
honest way to ship bars is to generate them.  The point of this module is that
the result should *look* right on a chart -- volatility that clusters, sessions
that are busy at the open and the close, trends that run and then stall, gaps
over the weekend, volume that spikes when price moves -- because a sample that
looks wrong teaches a user the wrong thing about the application.

It should also never be mistaken for real data.  So: every file starts with a
``# SYNTHETIC TEST DATA`` comment line, every generated file name carries the
word SYNTHETIC, and every :class:`BarSeries` produced here has
``meta["synthetic"] = True`` along with a plain-language warning string.

How the price process is put together
-------------------------------------

Log returns are the sum of three pieces plus noise:

``drift``
    A constant, calibrated from an annual return so a two-year sample of an
    equity index goes up by roughly what an equity index does.
``regime``
    A slow AR(1) component that switches between a *trending* mode (very
    persistent, so moves accumulate) and a *ranging* mode (fast reversion, so
    they cancel).  This is what makes a chart look like it has structure
    instead of being a pure random walk.
``volatility``
    A GARCH(1,1) variance -- quiet periods stay quiet, a big move makes the
    next move bigger -- multiplied by a time-of-day seasonality curve and a
    three-state volatility regime.  Shocks are Student-t with five degrees of
    freedom, standardised to unit variance, because normal tails produce a
    series with visibly too few outliers.

Each bar's high and low are then built by adding a strictly non-negative
excursion above and below the open/close body, which is what guarantees
``high >= max(open, close)`` and ``low <= min(open, close)`` for every bar
without any post-hoc repair.

Everything is drawn from one seeded :class:`numpy.random.Generator`, so the
same arguments always produce the same bars, on any machine.
"""

from __future__ import annotations

import copy
import logging
import math
import os
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import pandas as pd

from ..config import Workspace
from ..core.errors import DataError, StorageError
from ..core.timeframe import Timeframe, TimeframeUnit
from ..core.types import AssetClass
from .instruments import default_instrument_for
from .models import BarSeries, Instrument

log = logging.getLogger(__name__)

#: The first line of every generated CSV.  ``#`` is used deliberately: the CSV
#: loader treats a leading ``#`` as a comment, so the warning survives a
#: round trip through the importer without any special-casing.
SYNTHETIC_HEADER = ("# SYNTHETIC TEST DATA - generated by Trading Backtester - "
                    "NOT REAL MARKET DATA")

#: Value of ``BarSeries.source`` for generated bars.
SYNTHETIC_SOURCE = "SYNTHETIC (generated by Trading Backtester)"

#: Human-readable warning copied into ``BarSeries.meta``.
SYNTHETIC_WARNING = ("These bars were generated by a random process. They are "
                     "not real market data and must not be used to judge a "
                     "strategy's real-world performance.")

_TRADING_DAYS_PER_YEAR = 252.0
_WEEKDAYS_PER_YEAR = 260.0

#: Default first bar date.  Fixed rather than "today minus N" so that two runs
#: on different days produce identical files.
DEFAULT_START = "2020-01-02"

# Overnight gap parameters.  ``_GAP_SCALE`` is the gap's standard deviation as
# a fraction of a day's; the jump terms add the occasional news open.  The
# variance shares below are what the intraday process gives up in exchange, so
# that a day's total volatility still comes out where it was calibrated.
_GAP_SCALE = 0.55
_GAP_JUMP_P = 0.016
_GAP_SCALE_24H = 0.18
_GAP_JUMP_P_24H = 0.005
_GAP_JUMP_LO, _GAP_JUMP_HI = 1.2, 3.0

#: E[u^2] for u ~ Uniform(lo, hi) -- the variance a jump contributes when it hits.
_GAP_JUMP_MS = (_GAP_JUMP_HI ** 3 - _GAP_JUMP_LO ** 3) / (3.0 * (_GAP_JUMP_HI - _GAP_JUMP_LO))

#: Share of a day's variance that the opening gap accounts for.
_GAP_VARIANCE_SHARE = _GAP_SCALE ** 2 + _GAP_JUMP_P * _GAP_JUMP_MS
_GAP_VARIANCE_SHARE_24H = _GAP_SCALE_24H ** 2 + _GAP_JUMP_P_24H * _GAP_JUMP_MS


# ---------------------------------------------------------------------------
# Per-symbol character
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class MarketCharacter:
    """The handful of numbers that make one symbol look unlike another."""

    start_price: float
    annual_volatility: float
    annual_drift: float
    daily_volume: float
    """Typical volume for a whole session, in the instrument's own units."""


_CHARACTER: dict[str, MarketCharacter] = {
    "EURUSD": MarketCharacter(1.08500, 0.070, 0.000, 90_000),
    "GBPUSD": MarketCharacter(1.26500, 0.080, 0.000, 70_000),
    "AUDUSD": MarketCharacter(0.65500, 0.090, -0.010, 60_000),
    "USDJPY": MarketCharacter(152.400, 0.090, 0.020, 80_000),
    "BTCUSD": MarketCharacter(62_000.0, 0.550, 0.300, 22_000),
    "ETHUSD": MarketCharacter(3_200.00, 0.700, 0.220, 180_000),
    "SPY": MarketCharacter(505.00, 0.155, 0.090, 45_000_000),
    "QQQ": MarketCharacter(430.00, 0.200, 0.120, 30_000_000),
    "AAPL": MarketCharacter(190.00, 0.260, 0.130, 55_000_000),
    "TSLA": MarketCharacter(245.00, 0.500, 0.080, 90_000_000),
    "ES": MarketCharacter(5_200.00, 0.155, 0.085, 1_200_000),
    "NQ": MarketCharacter(18_200.00, 0.200, 0.115, 400_000),
    "MNQ": MarketCharacter(18_200.00, 0.200, 0.115, 900_000),
    "CL": MarketCharacter(78.50, 0.330, 0.020, 320_000),
    "GC": MarketCharacter(2_320.0, 0.140, 0.060, 180_000),
    "XAUUSD": MarketCharacter(2_320.00, 0.140, 0.060, 120_000),
}

_CLASS_CHARACTER: dict[AssetClass, MarketCharacter] = {
    AssetClass.FOREX: MarketCharacter(1.10000, 0.080, 0.0, 70_000),
    AssetClass.CRYPTO: MarketCharacter(1_000.00, 0.600, 0.20, 25_000),
    AssetClass.EQUITY: MarketCharacter(100.00, 0.240, 0.08, 5_000_000),
    AssetClass.FUTURES: MarketCharacter(5_000.00, 0.180, 0.07, 250_000),
    AssetClass.INDEX_CFD: MarketCharacter(5_000.00, 0.180, 0.07, 100_000),
    AssetClass.OTHER: MarketCharacter(100.00, 0.200, 0.05, 100_000),
}


def character_for(instrument: Instrument) -> MarketCharacter:
    """Starting price, volatility, drift and volume for one instrument."""
    known = _CHARACTER.get(instrument.symbol.upper())
    if known is not None:
        return known
    return _CLASS_CHARACTER.get(instrument.asset_class,
                                _CLASS_CHARACTER[AssetClass.OTHER])


# ---------------------------------------------------------------------------
# Sessions
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SessionProfile:
    """When an instrument trades, in its own timezone.

    ``round_the_clock`` instruments (spot FX, crypto) trade every hour of a
    weekday; the rest trade a bounded session, which is what produces the
    U-shaped intraday volatility curve.
    """

    timezone: str
    open_minute: int
    """Minutes after local midnight when the session opens."""
    close_minute: int
    """Minutes after local midnight when it closes; bars stop before this."""
    round_the_clock: bool = False
    week_close_minute: int | None = None
    """Local minute on Friday after which the market is shut for the weekend.

    Spot FX runs continuously from Monday morning to 17:00 New York on Friday,
    so without this a round-the-clock instrument would be given Friday evening
    bars that the real market does not have.
    """

    @property
    def length_minutes(self) -> int:
        return max(1, self.close_minute - self.open_minute)


def session_for(instrument: Instrument) -> SessionProfile:
    """The trading session used when generating bars for an instrument.

    Deliberately simple: US regular hours for shares, the CME regular-hours
    window for futures, and a full weekday for spot FX, metals and crypto.
    Generating the whole Globex session would add an overnight period whose
    thin liquidity this generator does not model anyway.
    """
    cls = instrument.asset_class
    if cls is AssetClass.EQUITY:
        return SessionProfile("America/New_York", 9 * 60 + 30, 16 * 60)
    if cls is AssetClass.FUTURES:
        # CME index and commodity regular hours, Chicago time.
        return SessionProfile("America/Chicago", 8 * 60 + 30, 15 * 60)
    if cls is AssetClass.INDEX_CFD:
        return SessionProfile("America/New_York", 9 * 60 + 30, 16 * 60)
    if cls is AssetClass.CRYPTO:
        return SessionProfile("UTC", 0, 24 * 60, round_the_clock=True)
    # Spot FX and spot metals: a full weekday in the timezone the instrument
    # names, which for the seeded catalogue is New York, ending at the 17:00
    # Friday close that the whole market observes.
    return SessionProfile(instrument.timezone or "UTC", 0, 24 * 60,
                          round_the_clock=True, week_close_minute=17 * 60)


def _bars_per_session(profile: SessionProfile, timeframe: Timeframe) -> int:
    """How many bars of this timeframe fit in one session."""
    seconds = timeframe.approx_seconds
    if seconds <= 0:  # pragma: no cover - Timeframe forbids it
        raise DataError("A timeframe must be longer than zero seconds.")
    return max(1, int(math.floor(profile.length_minutes * 60.0 / seconds)))


# ---------------------------------------------------------------------------
# Timestamps
# ---------------------------------------------------------------------------


def _session_timestamps(profile: SessionProfile, timeframe: Timeframe,
                        n_bars: int, start: str | datetime | pd.Timestamp) -> np.ndarray:
    """Build ``n_bars`` bar-open timestamps as int64 UTC nanoseconds.

    Weekends are skipped everywhere.  Intraday bars are laid on the session
    grid in the instrument's own timezone, so a session that starts at 09:30
    New York starts at 09:30 New York on both sides of a daylight-saving
    change rather than drifting by an hour.
    """
    if n_bars <= 0:
        raise DataError("A sample needs at least one bar.")
    try:
        first_day = pd.Timestamp(start).normalize()
    except (ValueError, TypeError) as exc:
        raise DataError(f"'{start}' is not a date this application can read.",
                        detail=repr(exc)) from exc
    if first_day.tz is not None:
        first_day = first_day.tz_convert(None)

    if timeframe.unit in (TimeframeUnit.DAY, TimeframeUnit.WEEK, TimeframeUnit.MONTH):
        return _calendar_timestamps(profile, timeframe, n_bars, first_day)

    per_day = _bars_per_session(profile, timeframe)
    step_ns = int(round(timeframe.approx_seconds * 1e9))
    offsets = np.arange(per_day, dtype="int64") * step_ns
    days_needed = int(math.ceil(n_bars / per_day)) + 4  # slack for the Friday close

    # Grow the calendar until it yields enough bars.  It usually fits first
    # time; the loop exists because the Friday close and daylight-saving
    # collisions both remove bars after the grid has been laid out.
    for _ in range(12):
        days = pd.bdate_range(start=first_day, periods=days_needed)
        opens = _localise(days + pd.Timedelta(minutes=profile.open_minute),
                          profile.timezone)
        grid = (opens[:, None] + offsets[None, :]).ravel()

        # A daylight-saving change makes a 24-hour "day" 23 or 25 hours long,
        # so for a round-the-clock instrument the last bar of one day can
        # collide with the first bar of the next.  Sorting and de-duplicating
        # is both the fix and the guarantee that ``ts`` comes out strictly
        # ascending.
        grid = np.unique(grid)
        grid = _apply_week_close(grid, profile)
        if grid.size >= n_bars:
            return np.ascontiguousarray(grid[:n_bars], dtype="int64")
        days_needed = int(days_needed * 1.4) + 5
    raise DataError(  # pragma: no cover - twelve rounds of growth is ample
        "That many bars could not be laid out on this instrument's session "
        "calendar.")


def _apply_week_close(grid: np.ndarray, profile: SessionProfile) -> np.ndarray:
    """Drop bars after the Friday close of a round-the-clock market."""
    if profile.week_close_minute is None or grid.size == 0:
        return grid
    local = pd.to_datetime(grid, utc=True).tz_convert(profile.timezone)
    minutes = local.hour.to_numpy(dtype="int64") * 60 + local.minute.to_numpy(dtype="int64")
    friday = local.weekday.to_numpy() == 4
    return grid[~(friday & (minutes >= profile.week_close_minute))]


def _calendar_timestamps(profile: SessionProfile, timeframe: Timeframe,
                         n_bars: int, first_day: pd.Timestamp) -> np.ndarray:
    """Daily, weekly and monthly bars, stamped at the session open."""
    if timeframe.unit is TimeframeUnit.DAY:
        step = max(1, timeframe.multiplier)
        days = pd.bdate_range(start=first_day, periods=n_bars * step)[::step][:n_bars]
    elif timeframe.unit is TimeframeUnit.WEEK:
        step = max(1, timeframe.multiplier)
        weeks = pd.date_range(start=first_day, periods=n_bars * step, freq="W-MON")
        days = weeks[::step][:n_bars]
    else:
        step = max(1, timeframe.multiplier)
        months = pd.date_range(start=first_day.replace(day=1),
                               periods=n_bars * step + 1, freq="MS")[::step][:n_bars]
        # The first business day of the month is when a monthly bar opens.
        days = pd.DatetimeIndex([
            m if m.weekday() < 5 else m + pd.Timedelta(days=7 - m.weekday())
            for m in months])
    stamps = _localise(pd.DatetimeIndex(days) + pd.Timedelta(minutes=profile.open_minute),
                       profile.timezone)
    if stamps.size < n_bars:  # pragma: no cover - ranges above are generous
        raise DataError("Not enough calendar time to generate that many bars.")
    return np.ascontiguousarray(stamps[:n_bars], dtype="int64")


def _localise(naive: pd.DatetimeIndex, tz_name: str) -> np.ndarray:
    """Read naive local timestamps in ``tz_name`` and return int64 UTC ns.

    ``nonexistent="shift_forward"`` and ``ambiguous=True`` resolve the two
    hours a year that do not exist or happen twice, instead of raising: a
    sample generator has no business failing on a clock change.
    """
    try:
        aware = naive.tz_localize(tz_name, nonexistent="shift_forward", ambiguous=True)
    except (ValueError, KeyError, TypeError) as exc:
        raise DataError(
            f"'{tz_name}' is not a timezone this computer knows about.",
            detail=repr(exc)) from exc
    return aware.tz_convert("UTC").to_numpy(dtype="datetime64[ns]").astype("int64")


# ---------------------------------------------------------------------------
# Seasonality
# ---------------------------------------------------------------------------


def _circular_bump(hours: np.ndarray, centre: float, width: float) -> np.ndarray:
    """A Gaussian bump on the 24-hour clock, so 23:00 is close to 01:00."""
    delta = np.abs(hours - centre)
    delta = np.minimum(delta, 24.0 - delta)
    return np.exp(-0.5 * (delta / width) ** 2)


def _intraday_profiles(minutes: np.ndarray, profile: SessionProfile,
                       instrument: Instrument) -> tuple[np.ndarray, np.ndarray]:
    """Volatility and volume multipliers for each bar, both averaging 1.0.

    For a bounded session this is the familiar U: heavy at the open, quiet
    around lunch, heavy again into the close.  For a round-the-clock
    instrument it is the two-humped FX day -- the London morning and the
    London/New York overlap -- with a quiet Asian afternoon.
    """
    hours = minutes / 60.0
    if profile.round_the_clock:
        if instrument.asset_class is AssetClass.CRYPTO:
            # Crypto is genuinely 24/7 but still wakes up for the US session.
            vol = (0.80 + 0.55 * _circular_bump(hours, 14.0, 3.0)
                   + 0.25 * _circular_bump(hours, 1.5, 2.0))
            turnover = (0.75 + 0.70 * _circular_bump(hours, 14.5, 3.0)
                        + 0.30 * _circular_bump(hours, 2.0, 2.5))
        else:
            # Hours are New York local: 03:00 is the London open, 08:00-12:00
            # the overlap, 19:00-21:00 the thin Sydney/Tokyo handover.
            vol = (0.42 + 0.85 * _circular_bump(hours, 3.0, 1.6)
                   + 1.25 * _circular_bump(hours, 9.5, 2.2)
                   + 0.30 * _circular_bump(hours, 20.0, 2.5))
            turnover = (0.35 + 0.95 * _circular_bump(hours, 3.5, 1.7)
                        + 1.40 * _circular_bump(hours, 10.0, 2.4)
                        + 0.25 * _circular_bump(hours, 20.0, 2.5))
    else:
        span = float(profile.length_minutes)
        x = np.clip((minutes - profile.open_minute) / span, 0.0, 1.0)
        vol = (0.62 + 1.70 * np.exp(-0.5 * (x / 0.10) ** 2)
               + 0.95 * np.exp(-0.5 * ((1.0 - x) / 0.09) ** 2))
        turnover = (0.45 + 1.60 * np.exp(-0.5 * (x / 0.09) ** 2)
                    + 2.10 * np.exp(-0.5 * ((1.0 - x) / 0.07) ** 2))

    # Normalise so the seasonality redistributes activity without changing the
    # total.  Volatility is normalised in *variance* terms -- mean of the
    # squares, not mean of the values -- because scaling returns by a curve
    # whose mean is one still raises their variance by the curve's dispersion,
    # and the calibrated annual volatility has to survive the shaping.
    vol = vol / max(math.sqrt(float(np.mean(vol ** 2))), 1e-12)
    turnover = turnover / max(float(np.mean(turnover)), 1e-12)
    return vol, turnover


# ---------------------------------------------------------------------------
# The generator
# ---------------------------------------------------------------------------


def generate_sample_data(symbol: str | Instrument = "EURUSD",
                         timeframe: Timeframe | str = "1h",
                         n_bars: int = 5_000,
                         *,
                         seed: int = 20200102,
                         start: str | datetime | pd.Timestamp = DEFAULT_START,
                         start_price: float | None = None,
                         annual_volatility: float | None = None,
                         annual_drift: float | None = None,
                         name: str = "") -> BarSeries:
    """Generate a deterministic synthetic :class:`BarSeries`.

    Parameters
    ----------
    symbol:
        A symbol from the seeded catalogue, or a full :class:`Instrument`.
    timeframe:
        Bar duration, as a :class:`Timeframe` or anything
        :meth:`Timeframe.parse` accepts (``"5m"``, ``"60m"``, ``"1D"``).
    n_bars:
        How many bars to produce.
    seed:
        Anything drawn here comes from ``numpy.random.default_rng(seed)``, so
        the same arguments always give the same bars.
    start:
        Date of the first bar.  Fixed by default so output is reproducible.
    start_price, annual_volatility, annual_drift:
        Override the symbol's character.  Volatility and drift are annualised
        fractions -- ``0.20`` is 20 percent.
    name:
        Dataset name recorded in ``meta``; defaults to ``SYNTHETIC <symbol> <tf>``.

    Returns
    -------
    BarSeries
        With ``meta["synthetic"] = True`` and every OHLC relationship valid.
    """
    instrument = _resolve_instrument(symbol)
    tf = timeframe if isinstance(timeframe, Timeframe) else Timeframe.parse(str(timeframe))
    count = _as_int(n_bars, "number of bars")
    if count < 2:
        raise DataError("A sample dataset needs at least two bars.")
    if count > 5_000_000:
        raise DataError("That is more sample bars than this generator will make "
                        "in one go; ask for five million or fewer.")

    profile = session_for(instrument)
    character = character_for(instrument)
    price0 = _as_float(start_price if start_price is not None
                       else character.start_price, "starting price")
    ann_vol = _as_float(annual_volatility if annual_volatility is not None
                        else character.annual_volatility, "annual volatility")
    ann_drift = _as_float(annual_drift if annual_drift is not None
                          else character.annual_drift, "annual drift")
    if price0 <= 0:
        raise DataError("A starting price must be greater than zero.")
    if ann_vol <= 0:
        raise DataError("Annual volatility must be greater than zero.")

    rng = np.random.default_rng(_as_int(seed, "seed"))
    ts = _session_timestamps(profile, tf, count, start)

    # Local wall-clock position of every bar, for seasonality and day breaks.
    local = pd.to_datetime(ts, utc=True).tz_convert(profile.timezone)
    minutes = (local.hour.to_numpy(dtype="float64") * 60.0
               + local.minute.to_numpy(dtype="float64"))
    day_id = np.asarray(local.normalize().tz_localize(None), dtype="datetime64[D]")
    new_day = np.empty(count, dtype=bool)
    new_day[0] = False  # nothing to gap from on the first bar
    new_day[1:] = day_id[1:] != day_id[:-1]

    intraday = tf.unit in (TimeframeUnit.SECOND, TimeframeUnit.MINUTE, TimeframeUnit.HOUR)
    if intraday:
        vol_season, turnover_season = _intraday_profiles(minutes, profile, instrument)
        bars_per_day = _bars_per_session(profile, tf)
    else:
        vol_season = np.ones(count)
        turnover_season = np.ones(count)
        bars_per_day = 1

    days_per_year = _WEEKDAYS_PER_YEAR if profile.round_the_clock else _TRADING_DAYS_PER_YEAR
    if tf.unit is TimeframeUnit.WEEK:
        bars_per_year = 52.0 / tf.multiplier
    elif tf.unit is TimeframeUnit.MONTH:
        bars_per_year = 12.0 / tf.multiplier
    elif intraday:
        bars_per_year = days_per_year * bars_per_day
    else:  # daily bars, possibly several days each
        bars_per_year = days_per_year / tf.multiplier
    bars_per_year = max(bars_per_year, 1.0)

    # The overnight gap carries a share of each day's variance rather than
    # being added on top of it, so shrink the per-bar volatility by that share:
    # a market that gaps 5 percent of the way to its daily range should not
    # also move a full day's worth inside the session.
    gap_share = _GAP_VARIANCE_SHARE_24H if profile.round_the_clock else _GAP_VARIANCE_SHARE
    sigma0 = ann_vol / math.sqrt(bars_per_year) / math.sqrt(1.0 + gap_share)
    # Log-return drift: subtracting half the variance makes the *arithmetic*
    # annual return come out at ``annual_drift`` rather than overshooting it.
    drift = (ann_drift - 0.5 * ann_vol * ann_vol) / bars_per_year

    returns, sigma_used, sigma_state = _return_path(rng, count, sigma0, drift, vol_season)
    gaps = _overnight_gaps(rng, new_day, sigma_state, bars_per_day, profile)

    log_start = math.log(price0)
    cumulative = np.cumsum(gaps + returns)
    close_log = log_start + cumulative
    open_log = log_start + (cumulative - returns)

    high_log, low_log = _intrabar_range(rng, open_log, close_log, sigma_used)

    open_ = np.exp(open_log)
    close = np.exp(close_log)
    high = np.exp(high_log)
    low = np.exp(low_log)
    volume = _volume(rng, returns, sigma_used, turnover_season,
                     character.daily_volume, bars_per_day, instrument)

    open_, high, low, close = _snap_to_tick(instrument, open_, high, low, close)

    bars = BarSeries(
        ts=ts, open=open_, high=high, low=low, close=close, volume=volume,
        instrument=instrument, timeframe=tf, source=SYNTHETIC_SOURCE,
        meta={
            "synthetic": True,
            "data_warning": SYNTHETIC_WARNING,
            "generator": "tradingbacktester.data.sample.generate_sample_data",
            "name": name or f"SYNTHETIC {instrument.symbol} {tf.label}",
            "seed": int(seed),
            "start": str(start),
            "annual_volatility": ann_vol,
            "annual_drift": ann_drift,
            "start_price": price0,
            "session": f"{profile.open_minute // 60:02d}:{profile.open_minute % 60:02d}"
                       f"-{profile.close_minute // 60:02d}:{profile.close_minute % 60:02d} "
                       f"{profile.timezone}",
            "generated_by": "Trading Backtester",
        },
    )
    log.info("Generated %s (seed %d)", bars.describe(), seed)
    return bars


def _as_int(value: Any, what: str) -> int:
    """Convert a caller's number, turning a bad one into a :class:`DataError`.

    The generator is driven from the UI, where every setting arrives as text;
    a raw ``ValueError`` from ``int()`` would reach the user as a traceback.
    """
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise DataError(f"The {what} must be a whole number, not '{value}'.",
                        detail=repr(exc)) from exc


def _as_float(value: Any, what: str) -> float:
    """Convert a caller's number, turning a bad one into a :class:`DataError`."""
    try:
        result = float(value)
    except (TypeError, ValueError) as exc:
        raise DataError(f"The {what} must be a number, not '{value}'.",
                        detail=repr(exc)) from exc
    if not math.isfinite(result):
        raise DataError(f"The {what} must be a finite number.")
    return result


def _resolve_instrument(symbol: str | Instrument) -> Instrument:
    """Accept a symbol or a full instrument; never hand back a shared object."""
    if isinstance(symbol, Instrument):
        return copy.deepcopy(symbol)
    key = str(symbol).strip().upper()
    if not key:
        raise DataError("A sample dataset needs a symbol.")
    seeded = default_instrument_for(key)
    if seeded is not None:
        return seeded
    log.info("No seeded contract specification for %s; using generic defaults", key)
    return Instrument(symbol=key)


def _return_path(rng: np.random.Generator, n: int, sigma0: float, drift: float,
                 vol_season: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Log returns, the volatility that produced each one, and the regime level.

    The third array is the volatility *without* the time-of-day seasonality:
    it is what the overnight gap is scaled by, so that gaps grow in a stressed
    market the way real ones do.

    The loop is unavoidable: GARCH variance, the AR(1) drift and the two
    Markov chains each depend on their own previous value.  Every random draw
    is made up-front as an array, so the loop itself is pure arithmetic and
    stays O(n).
    """
    # alpha + beta = 0.97 is a realistically slow decay, and alpha this size is
    # what makes the clustering visible on a chart.  With t(7) shocks the
    # fourth moment stays finite (alpha^2*E[z^4] + 2*alpha*beta + beta^2 < 1),
    # so the variance process does not wander off.
    alpha, beta = 0.11, 0.86
    omega = sigma0 * sigma0 * (1.0 - alpha - beta)
    var_cap = (7.0 * sigma0) ** 2       # keeps a fat-tailed shock from exploding

    # Student-t shocks, standardised to unit variance: fatter tails than a
    # normal, which is what makes the extremes on the chart look believable.
    df = 7.0
    shocks = rng.standard_t(df, n) / math.sqrt(df / (df - 2.0))

    # Trend / range regime.  Expected episode lengths of a few hundred bars.
    p_trend_switch = 1.0 / 400.0
    u_trend = rng.random(n)
    phi_trend, phi_range = 0.997, 0.94
    sd_trend = 0.055 * sigma0 * math.sqrt(1.0 - phi_trend ** 2)
    sd_range = 0.020 * sigma0 * math.sqrt(1.0 - phi_range ** 2)
    z_mu = rng.standard_normal(n)

    # Volatility regime: calm, normal, stressed.  The states are rescaled so
    # that their probability-weighted mean *square* is one, which keeps the
    # long-run realised volatility on the number it was calibrated to instead
    # of a few percent above it.
    vol_weights = np.array([0.35, 0.50, 0.15])
    vol_states = np.array([0.72, 1.0, 1.75])
    vol_states = vol_states / math.sqrt(float(np.sum(vol_weights * vol_states ** 2)))
    p_vol_switch = 1.0 / 500.0
    u_vol = rng.random(n)
    k_vol = rng.choice(len(vol_states), size=n, p=vol_weights)

    returns = np.empty(n, dtype="float64")
    sigma_used = np.empty(n, dtype="float64")
    sigma_state = np.empty(n, dtype="float64")

    variance = sigma0 * sigma0
    mu = 0.0
    trending = False
    vol_level = 1.0

    for i in range(n):
        if u_trend[i] < p_trend_switch:
            trending = not trending
        if u_vol[i] < p_vol_switch:
            vol_level = float(vol_states[k_vol[i]])

        if trending:
            mu = phi_trend * mu + sd_trend * z_mu[i]
        else:
            mu = phi_range * mu + sd_range * z_mu[i]

        level = math.sqrt(variance) * vol_level
        sigma = level * vol_season[i]
        returns[i] = drift + mu + sigma * shocks[i]
        sigma_used[i] = sigma
        sigma_state[i] = level

        # GARCH is updated with the *standardised* shock so the intraday
        # seasonality shapes each bar without feeding back into the variance
        # process, which would double-count the time-of-day effect.
        variance = omega + alpha * variance * shocks[i] ** 2 + beta * variance
        if variance > var_cap:
            variance = var_cap

    return returns, sigma_used, sigma_state


def _overnight_gaps(rng: np.random.Generator, new_day: np.ndarray,
                    sigma_state: np.ndarray, bars_per_day: int,
                    profile: SessionProfile) -> np.ndarray:
    """Jumps between one session's close and the next session's open.

    A market that closes overnight gaps every morning; one that never closes
    only really gaps over the weekend, so its gaps are much smaller.  Gaps are
    scaled by the volatility *regime* rather than by a constant, because a
    market that is moving 3 percent a day does not open 0.2 percent away from
    where it closed -- and because a constant would dilute the volatility
    clustering that the rest of the process works to produce.
    """
    gaps = np.zeros(new_day.size, dtype="float64")
    idx = np.flatnonzero(new_day)
    if idx.size == 0:
        return gaps

    daily_sigma = sigma_state[idx] * math.sqrt(max(1, bars_per_day))
    if profile.round_the_clock:
        scale, jump_p = _GAP_SCALE_24H, _GAP_JUMP_P_24H
    else:
        scale, jump_p = _GAP_SCALE, _GAP_JUMP_P
    body = rng.standard_normal(idx.size) * daily_sigma * scale

    # Roughly one session in sixty opens on news rather than on drift.
    jump_hit = rng.random(idx.size) < jump_p
    jump_size = (rng.uniform(_GAP_JUMP_LO, _GAP_JUMP_HI, idx.size)
                 * np.where(rng.random(idx.size) < 0.5, -1.0, 1.0)
                 * daily_sigma)
    gaps[idx] = body + np.where(jump_hit, jump_size, 0.0)
    return gaps


def _intrabar_range(rng: np.random.Generator, open_log: np.ndarray,
                    close_log: np.ndarray,
                    sigma_used: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """High and low in log space, guaranteed to bracket the open and close.

    The excursion beyond the body is drawn as a non-negative quantity and then
    split between the two sides, which is what makes
    ``high >= max(open, close)`` and ``low <= min(open, close)`` true by
    construction rather than by repair.  Wicks are biased in the direction of
    the bar, because a bar that closes up usually pushed higher first.
    """
    n = open_log.size
    body_top = np.maximum(open_log, close_log)
    body_bottom = np.minimum(open_log, close_log)
    body = body_top - body_bottom

    # Half-normal excursion plus a share of the body: a bar with a big body
    # has bigger wicks in absolute terms, which is what real bars look like.
    excursion = np.abs(rng.standard_normal(n)) * sigma_used * 0.85 + 0.18 * body

    direction = np.sign(close_log - open_log)
    share = np.clip(rng.beta(2.4, 2.4, n) + 0.12 * direction, 0.05, 0.95)

    high_log = body_top + share * excursion
    low_log = body_bottom - (1.0 - share) * excursion
    return high_log, low_log


def _volume(rng: np.random.Generator, returns: np.ndarray, sigma_used: np.ndarray,
            turnover_season: np.ndarray, daily_volume: float, bars_per_day: int,
            instrument: Instrument) -> np.ndarray:
    """Volume that rises with the time of day and with the size of the move.

    Real volume and absolute return are strongly positively correlated; the
    lognormal factor supplies the dispersion that stops the relationship from
    looking like a straight line.
    """
    per_bar = max(daily_volume / max(1, bars_per_day), 1.0)
    with np.errstate(divide="ignore", invalid="ignore"):
        standardised = np.abs(np.divide(returns, sigma_used,
                                        out=np.zeros_like(returns),
                                        where=sigma_used > 0))
    standardised = np.clip(standardised, 0.0, 8.0)
    noise = np.exp(rng.normal(0.0, 0.35, returns.size) - 0.5 * 0.35 ** 2)
    raw = per_bar * turnover_season * (0.55 + 0.75 * standardised) * noise

    if instrument.asset_class is AssetClass.CRYPTO:
        # Coins trade in fractions; keep three decimals rather than rounding a
        # thinly traded bar down to a whole coin.
        volume = np.maximum(np.round(raw, 3), 0.001)
    else:
        volume = np.maximum(np.round(raw), 1.0)
    return np.ascontiguousarray(volume, dtype="float64")


def _snap_to_tick(instrument: Instrument, open_: np.ndarray, high: np.ndarray,
                  low: np.ndarray, close: np.ndarray
                  ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Round every price to the instrument's tick grid.

    Rounding to a grid is monotone, so it cannot invert ``high >= open`` -- but
    the maximum and minimum are re-applied anyway, because an invariant that
    the rest of the application relies on should not depend on a floating-point
    argument being right.
    """
    tick = float(instrument.tick_size)
    if tick > 0:
        open_ = np.round(open_ / tick) * tick
        high = np.round(high / tick) * tick
        low = np.round(low / tick) * tick
        close = np.round(close / tick) * tick
        floor = tick
    else:  # pragma: no cover - Instrument forbids a non-positive tick
        floor = 1e-9

    high = np.maximum.reduce([high, open_, close])
    low = np.minimum.reduce([low, open_, close])
    low = np.maximum(low, floor)
    high = np.maximum(high, low)
    return (np.ascontiguousarray(open_), np.ascontiguousarray(high),
            np.ascontiguousarray(low), np.ascontiguousarray(close))


# ---------------------------------------------------------------------------
# CSV output
# ---------------------------------------------------------------------------


def write_sample_csv(path: str | Path, bars: BarSeries | None = None,
                     **generate_kwargs: Any) -> Path:
    """Write a synthetic dataset to a CSV file.

    The first line is :data:`SYNTHETIC_HEADER`, a ``#`` comment that the CSV
    loader skips, so a user who opens the file in a text editor or a
    spreadsheet is told what it is before they read a single price.

    Parameters
    ----------
    path:
        Destination file.
    bars:
        Bars to write.  When omitted they are generated by passing the
        remaining keyword arguments to :func:`generate_sample_data`.

    Returns
    -------
    Path
        The file that was written.
    """
    target = Path(path).expanduser()
    series = bars if bars is not None else generate_sample_data(**generate_kwargs)
    if len(series) == 0:
        raise DataError("There are no bars to write.")
    if not series.meta.get("synthetic"):
        # This function's whole contract is "this file is clearly synthetic";
        # writing real bars through it would put a false warning on real data.
        raise DataError(
            "write_sample_csv only writes generated data. Use the CSV export "
            "in the Reports menu to write real market data.")

    decimals = max(0, int(series.instrument.price_decimals))
    stamps = pd.to_datetime(series.ts, utc=True).strftime("%Y-%m-%d %H:%M:%S%z")
    # Each column is formatted explicitly rather than through ``float_format``,
    # which would print volume with five decimal places on a five-decimal FX
    # instrument.
    price_fmt = f"%.{decimals}f"
    volume_integral = bool(np.all(series.volume == np.round(series.volume)))
    frame = pd.DataFrame({
        "datetime": np.asarray(stamps, dtype=object),
        "open": np.char.mod(price_fmt, series.open),
        "high": np.char.mod(price_fmt, series.high),
        "low": np.char.mod(price_fmt, series.low),
        "close": np.char.mod(price_fmt, series.close),
        "volume": (np.char.mod("%d", series.volume) if volume_integral
                   else np.char.mod("%.3f", series.volume)),
    })

    body = frame.to_csv(index=False, lineterminator="\n")
    text = (f"{SYNTHETIC_HEADER}\n"
            f"# {series.instrument.symbol} {series.timeframe.label}, "
            f"{len(series):,} bars, seed {series.meta.get('seed', 'n/a')}\n"
            f"{body}")
    _atomic_write_text(target, text)
    log.info("Wrote %s (%d bars)", target, len(series))
    return target


def _atomic_write_text(path: Path, text: str) -> None:
    """Write text through a temporary file so a failure cannot truncate a good one."""
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp",
                                        dir=str(path.parent))
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(text)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(tmp_name, path)
        except BaseException:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise
    except OSError as exc:
        raise StorageError(
            f"The file {path.name} could not be written to {path.parent}.\n\n"
            f"Check that the folder exists and that there is free space.",
            detail=repr(exc)) from exc


# ---------------------------------------------------------------------------
# The bundled samples
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SampleSpec:
    """One of the datasets shipped with a fresh workspace."""

    filename: str
    symbol: str
    timeframe: str
    n_bars: int
    seed: int
    start: str

    def describe(self) -> str:
        return f"{self.symbol} {self.timeframe}, {self.n_bars:,} synthetic bars"


#: The three bundled samples: one round-the-clock FX series, one intraday
#: futures series on a bounded session, and one daily equity series.  Between
#: them they exercise every path in the generator and every timeframe shape the
#: rest of the application has to cope with.
SAMPLE_SPECS: tuple[SampleSpec, ...] = (
    SampleSpec("SYNTHETIC_EURUSD_60m.csv", "EURUSD", "60m", 12_000, 101, "2023-01-02"),
    SampleSpec("SYNTHETIC_NQ_5m.csv", "NQ", "5m", 20_000, 202, "2024-01-02"),
    SampleSpec("SYNTHETIC_SPY_1D.csv", "SPY", "1D", 1_500, 303, "2019-01-02"),
)


def ensure_samples(workspace: Workspace | str | Path, force: bool = False) -> list[Path]:
    """Create the bundled sample files in the workspace if they are not there.

    Called on every start-up, so it is cheap when the files already exist: a
    sample is only regenerated when it is missing, or when ``force`` is set
    because the user asked for the originals back.

    Returns the paths of all three samples, whether or not they were written
    this time.  A sample that cannot be written is logged and skipped rather
    than stopping the application from starting -- the workspace may be on a
    read-only volume.
    """
    space = workspace if isinstance(workspace, Workspace) else Workspace(Path(workspace))
    folder = space.samples
    try:
        folder.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise StorageError(
            f"The samples folder could not be created at {folder}.",
            detail=repr(exc)) from exc

    written: list[Path] = []
    for spec in SAMPLE_SPECS:
        target = folder / spec.filename
        if target.exists() and not force:
            written.append(target)
            continue
        try:
            bars = generate_sample_data(spec.symbol, spec.timeframe, spec.n_bars,
                                        seed=spec.seed, start=spec.start,
                                        name=Path(spec.filename).stem)
            write_sample_csv(target, bars)
            written.append(target)
        except (DataError, StorageError) as exc:
            log.error("The sample %s could not be created: %s", spec.filename, exc)
        except Exception as exc:  # noqa: BLE001 - start-up must not be blocked
            log.exception("Unexpected failure generating the sample %s: %r",
                          spec.filename, exc)
    return written


def sample_paths(workspace: Workspace | str | Path) -> list[Path]:
    """Where the bundled samples live, whether or not they exist yet."""
    space = workspace if isinstance(workspace, Workspace) else Workspace(Path(workspace))
    return [space.samples / spec.filename for spec in SAMPLE_SPECS]


def describe_samples() -> Sequence[str]:
    """One line per bundled sample, for an about box or the log."""
    return [f"{spec.filename}: {spec.describe()}" for spec in SAMPLE_SPECS]


def is_synthetic(bars: BarSeries) -> bool:
    """True when a series was produced by this module.

    Reports and the window title use it to keep the SYNTHETIC label attached to
    results computed from generated data.
    """
    return bool(bars.meta.get("synthetic")) or bars.source == SYNTHETIC_SOURCE
